---
- name: Add reaper.py to Supervisor
  supervisorctl: name="reaper.py"
                 state=present
  sudo: yes
  sudo_user: root

- name: Restart reaper.py
  supervisorctl: name="reaper.py"
                 state=restarted
  sudo: yes
  sudo_user: root