services:
  sphinx:
    build:
      context: ../..  # project root
      dockerfile: docs/docker/Dockerfile
    volumes:
      #- ../../docs/source:/docs/source  # Mount the `docs/source` folder to allow live editing
      #- ../../demos:/docs/source/demos  # Mount the `demos` folder for live editing
      - ../../docs/_build:/docs/_build  # Mount the Sphinx build output to a directory on the host
      - ../../docs/doctrees:/docs/doctrees  # Mount doctrees to persist build state
    environment:
      - USER_ID=${UID}  # Pass user ID for permission handling
      - DOCS_FORMAT=${DOCS_FORMAT:-all}  # Pass DOCS_FORMAT to enable specific format builds
