FROM graphistry/cpu-base:6.7
ENV graphistry_install_path "/var/graphistry"
ENV graphistry_temp_path "/tmp/graphistry"
RUN mkdir -p /var/log/graphistry-json $graphistry_temp_path $graphistry_install_path \
             /var/log/central-app /var/log/clients /var/log/worker /var/log/graphistry-json /var/log/reaper /root/.ssh

WORKDIR $graphistry_install_path

RUN apt-get update && apt-get install -y default-jre-headless pigz && rm -rf /var/lib/apt/lists/*

RUN curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/github/id_rsa > /root/.ssh/id_rsa && \
    curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/github/id_rsa.pub > /root/.ssh/id_rsa.pub && \
    curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/npm/rc > /root/.npmrc && \
    chmod 400 /root/.ssh/* && \
    (ssh -o StrictHostKeyChecking=no -T git@github.com || true) && \
    git clone git@github.com:graphistry/viz-app.git && \
    cd viz-app && \
    npm install && \
    npm run build

WORKDIR $graphistry_install_path/viz-app

CMD npm run serve "{\"VIZ_LISTEN_ADDRESS\":\"0.0.0.0\", \"VIZ_LISTEN_PORT\": 80, \"GRAPHISTRY_LOG_LEVEL\": \"DEBUG\"}"
