FROM graphistry/baseapp:1.1
ENV graphistry_install_path "/var/graphistry"
ENV graphistry_temp_path "/tmp/graphistry"
ENV workers_count 2
ENV workers_port_start 10000
ENV upload_limit "128M"
ENV GRAPHISTRY_LOG_LEVEL INFO

RUN mkdir -p /var/log/graphistry-json $graphistry_temp_path $graphistry_install_path \
             /var/log/central-app /var/log/clients /var/log/worker /var/log/graphistry-json /var/log/reaper /root/.ssh

# logrotate.

COPY logrotate.conf /etc/logrotate.d/graphistry.conf

# reaper.

COPY reaper.py $graphistry_install_path

# supervisor.

COPY central.conf viz_workers.conf reaper.conf /etc/supervisor/conf.d/
COPY supervisord.conf /etc/supervisor
CMD bash -l -c "supervisord -n -c /etc/supervisor/supervisord.conf"

# fetch secrets from our vault, do the npm installs, and delete the secrets.

RUN curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/github/id_rsa > /root/.ssh/id_rsa && \
    curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/github/id_rsa.pub > /root/.ssh/id_rsa.pub && \
    curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/npm/rc > /root/.npmrc && \
    chmod 400 /root/.ssh/* && \
    (ssh -o StrictHostKeyChecking=no -T git@github.com || true) && \
    cd $graphistry_install_path && \
    npm install @graphistry/central && \
    bash -l -c "npm install @graphistry/viz-app" && \
    git clone git@github.com:graphistry/datasets.git && \
    mv datasets/preloaded/* node_modules/@graphistry/central/assets/ && \
    rm -rf datasets && \
    mv node_modules/@graphistry/central/assets/index-without-s3.html node_modules/@graphistry/central/assets/index.html && \
    rm -r /tmp/* && \
    sed -i -E -e "s/accessKeyId: '.+', secretAccessKey: '.+'/accessKeyId: null, secretAccessKey: null/" -e "s/SLACK_BOT_ETL_TOKEN: '.+'/SLACK_BOT_ETL_TOKEN: null/" -e "s/SECRET: '.+'/SECRET: 'IQT'/" $(find -L . -name index.js | grep '@graphistry/config/index.js') && \
    shred -u /root/.ssh/* /root/.npmrc
