from graphistry.compute import e_forward, e_undirected, n

from tests.cypher_tck.models import Expected, GraphFixture, Scenario
from tests.cypher_tck.parse_cypher import graph_fixture_from_create

from tests.cypher_tck.scenarios.fixtures import (
    MATCH5_GRAPH,
    MATCH7_GRAPH_SINGLE,
    MATCH7_GRAPH_AB,
    MATCH7_GRAPH_ABC,
    MATCH7_GRAPH_REL,
    MATCH7_GRAPH_X,
    MATCH7_GRAPH_AB_X,
    MATCH7_GRAPH_LABELS,
    MATCH7_GRAPH_PLAYER_TEAM_BOTH,
    MATCH7_GRAPH_PLAYER_TEAM_SINGLE,
    MATCH7_GRAPH_PLAYER_TEAM_DIFF,
    WITH_ORDERBY4_GRAPH,
    BINARY_TREE_1_GRAPH,
    BINARY_TREE_2_GRAPH,
)


SCENARIOS = [
    Scenario(
        key="match5-1",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[1] Handling unbounded variable length match",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
                {"c.name": "'n0000'"},
                {"c.name": "'n0001'"},
                {"c.name": "'n0010'"},
                {"c.name": "'n0011'"},
                {"c.name": "'n0100'"},
                {"c.name": "'n0101'"},
                {"c.name": "'n0110'"},
                {"c.name": "'n0111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-2",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[2] Handling explicitly unbounded variable length match",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*..]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
                {"c.name": "'n0000'"},
                {"c.name": "'n0001'"},
                {"c.name": "'n0010'"},
                {"c.name": "'n0011'"},
                {"c.name": "'n0100'"},
                {"c.name": "'n0101'"},
                {"c.name": "'n0110'"},
                {"c.name": "'n0111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-3",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[3] Handling single bounded variable length match 1",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*0]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n0'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-4",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[4] Handling single bounded variable length match 2",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*1]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-5",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[5] Handling single bounded variable length match 3",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*2]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-6",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[6] Handling upper and lower bounded variable length match 1",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*0..2]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n0'"},
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-7",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[7] Handling upper and lower bounded variable length match 2",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*1..2]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-8",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[8] Handling symmetrically bounded variable length match, bounds are zero",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*0..0]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n0'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-9",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[9] Handling symmetrically bounded variable length match, bounds are one",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*1..1]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-10",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[10] Handling symmetrically bounded variable length match, bounds are two",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*2..2]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-11",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[11] Handling upper and lower bounded variable length match, empty interval 1",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*2..1]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(rows=[]),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-12",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[12] Handling upper and lower bounded variable length match, empty interval 2",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*1..0]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(rows=[]),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-13",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[13] Handling upper bounded variable length match, empty interval",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*..0]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(rows=[]),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-14",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[14] Handling upper bounded variable length match 1",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*..1]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-15",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[15] Handling upper bounded variable length match 2",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*..2]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-16",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[16] Handling lower bounded variable length match 1",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*0..]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n0'"},
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
                {"c.name": "'n0000'"},
                {"c.name": "'n0001'"},
                {"c.name": "'n0010'"},
                {"c.name": "'n0011'"},
                {"c.name": "'n0100'"},
                {"c.name": "'n0101'"},
                {"c.name": "'n0110'"},
                {"c.name": "'n0111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-17",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[17] Handling lower bounded variable length match 2",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*1..]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
                {"c.name": "'n0000'"},
                {"c.name": "'n0001'"},
                {"c.name": "'n0010'"},
                {"c.name": "'n0011'"},
                {"c.name": "'n0100'"},
                {"c.name": "'n0101'"},
                {"c.name": "'n0110'"},
                {"c.name": "'n0111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-18",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[18] Handling lower bounded variable length match 3",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*2..]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
                {"c.name": "'n0000'"},
                {"c.name": "'n0001'"},
                {"c.name": "'n0010'"},
                {"c.name": "'n0011'"},
                {"c.name": "'n0100'"},
                {"c.name": "'n0101'"},
                {"c.name": "'n0110'"},
                {"c.name": "'n0111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-19",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[19] Handling a variable length relationship and a standard relationship in chain, zero length 1",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*0]->()-[:LIKES]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-20",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[20] Handling a variable length relationship and a standard relationship in chain, zero length 2",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES]->()-[:LIKES*0]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00'"},
                {"c.name": "'n01'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-21",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[21] Handling a variable length relationship and a standard relationship in chain, single length 1",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*1]->()-[:LIKES]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-22",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[22] Handling a variable length relationship and a standard relationship in chain, single length 2",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES]->()-[:LIKES*1]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n000'"},
                {"c.name": "'n001'"},
                {"c.name": "'n010'"},
                {"c.name": "'n011'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-23",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[23] Handling a variable length relationship and a standard relationship in chain, longer 1",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES*2]->()-[:LIKES]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n0000'"},
                {"c.name": "'n0001'"},
                {"c.name": "'n0010'"},
                {"c.name": "'n0011'"},
                {"c.name": "'n0100'"},
                {"c.name": "'n0101'"},
                {"c.name": "'n0110'"},
                {"c.name": "'n0111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-24",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[24] Handling a variable length relationship and a standard relationship in chain, longer 2",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES]->()-[:LIKES*2]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n0000'"},
                {"c.name": "'n0001'"},
                {"c.name": "'n0010'"},
                {"c.name": "'n0011'"},
                {"c.name": "'n0100'"},
                {"c.name": "'n0101'"},
                {"c.name": "'n0110'"},
                {"c.name": "'n0111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and row projections are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-25",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[25] Handling a variable length relationship and a standard relationship in chain, longer 3",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES]->()-[:LIKES*3]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00000'"},
                {"c.name": "'n00001'"},
                {"c.name": "'n00010'"},
                {"c.name": "'n00011'"},
                {"c.name": "'n00100'"},
                {"c.name": "'n00101'"},
                {"c.name": "'n00110'"},
                {"c.name": "'n00111'"},
                {"c.name": "'n01000'"},
                {"c.name": "'n01001'"},
                {"c.name": "'n01010'"},
                {"c.name": "'n01011'"},
                {"c.name": "'n01100'"},
                {"c.name": "'n01101'"},
                {"c.name": "'n01110'"},
                {"c.name": "'n01111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and MATCH/CREATE setup expressions are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-26",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[26] Handling mixed relationship patterns and directions 1",
        cypher="MATCH (a:A)\nMATCH (a)<-[:LIKES]-()-[:LIKES*3]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00000'"},
                {"c.name": "'n00001'"},
                {"c.name": "'n00010'"},
                {"c.name": "'n00011'"},
                {"c.name": "'n00100'"},
                {"c.name": "'n00101'"},
                {"c.name": "'n00110'"},
                {"c.name": "'n00111'"},
                {"c.name": "'n01000'"},
                {"c.name": "'n01001'"},
                {"c.name": "'n01010'"},
                {"c.name": "'n01011'"},
                {"c.name": "'n01100'"},
                {"c.name": "'n01101'"},
                {"c.name": "'n01110'"},
                {"c.name": "'n01111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching, direction mixing, and MATCH/DELETE/CREATE setup are not supported",
        tags=("match", "variable-length", "direction", "xfail"),
    ),

    Scenario(
        key="match5-27",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[27] Handling mixed relationship patterns and directions 2",
        cypher="MATCH (a:A)\nMATCH (a)-[:LIKES]->()<-[:LIKES*3]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00000'"},
                {"c.name": "'n00001'"},
                {"c.name": "'n00010'"},
                {"c.name": "'n00011'"},
                {"c.name": "'n00100'"},
                {"c.name": "'n00101'"},
                {"c.name": "'n00110'"},
                {"c.name": "'n00111'"},
                {"c.name": "'n01000'"},
                {"c.name": "'n01001'"},
                {"c.name": "'n01010'"},
                {"c.name": "'n01011'"},
                {"c.name": "'n01100'"},
                {"c.name": "'n01101'"},
                {"c.name": "'n01110'"},
                {"c.name": "'n01111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching, direction mixing, and MATCH/DELETE/CREATE setup are not supported",
        tags=("match", "variable-length", "direction", "xfail"),
    ),

    Scenario(
        key="match5-28",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[28] Handling mixed relationship patterns 1",
        cypher="MATCH (a:A)\nMATCH (p)-[:LIKES*1]->()-[:LIKES]->()-[r:LIKES*2]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00000'"},
                {"c.name": "'n00001'"},
                {"c.name": "'n00010'"},
                {"c.name": "'n00011'"},
                {"c.name": "'n00100'"},
                {"c.name": "'n00101'"},
                {"c.name": "'n00110'"},
                {"c.name": "'n00111'"},
                {"c.name": "'n01000'"},
                {"c.name": "'n01001'"},
                {"c.name": "'n01010'"},
                {"c.name": "'n01011'"},
                {"c.name": "'n01100'"},
                {"c.name": "'n01101'"},
                {"c.name": "'n01110'"},
                {"c.name": "'n01111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and MATCH/CREATE setup expressions are not supported",
        tags=("match", "variable-length", "xfail"),
    ),

    Scenario(
        key="match5-29",
        feature_path="tck/features/clauses/match/Match5.feature",
        scenario="[29] Handling mixed relationship patterns 2",
        cypher="MATCH (a:A)\nMATCH (p)-[:LIKES]->()-[:LIKES*2]->()-[r:LIKES]->(c)\nRETURN c.name",
        graph=MATCH5_GRAPH,
        expected=Expected(
            rows=[
                {"c.name": "'n00000'"},
                {"c.name": "'n00001'"},
                {"c.name": "'n00010'"},
                {"c.name": "'n00011'"},
                {"c.name": "'n00100'"},
                {"c.name": "'n00101'"},
                {"c.name": "'n00110'"},
                {"c.name": "'n00111'"},
                {"c.name": "'n01000'"},
                {"c.name": "'n01001'"},
                {"c.name": "'n01010'"},
                {"c.name": "'n01011'"},
                {"c.name": "'n01100'"},
                {"c.name": "'n01101'"},
                {"c.name": "'n01110'"},
                {"c.name": "'n01111'"},
            ],
        ),
        gfql=None,
        status="xfail",
        reason="Variable-length relationship matching and MATCH/CREATE setup expressions are not supported",
        tags=("match", "variable-length", "xfail"),
    ),
]
