---
- name: Restart Supervisor
  # Bug: Ansible will sometimes fail when restarting Supervisor if a sleep time isn't specified.
  # Cause: Ansible performs a service 'restart' by stopping, then starting the service, but
  # Supervisor's init.d script returns before the action finishes, causing the `start` to fail
  # because the `stop` is still in progress. Supervisor's init.d script specifies a sleep of 5s
  # between stop & start for it's native `restart` action, so we include that below.
  service: name=supervisor
           state=restarted
           sleep=5
  sudo: yes
  sudo_user: root