FROM graphistry/baseapp:1.2
ENV graphistry_install_path "/var/graphistry"
ENV graphistry_temp_path "/tmp/graphistry"
RUN mkdir -p /var/log/graphistry-json $graphistry_temp_path $graphistry_install_path \
             /var/log/central-app /var/log/clients /var/log/worker /var/log/graphistry-json /var/log/reaper /root/.ssh

WORKDIR $graphistry_install_path

RUN curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/github/id_rsa > /root/.ssh/id_rsa && \
    curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/github/id_rsa.pub > /root/.ssh/id_rsa.pub && \
    curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/npm/rc > /root/.npmrc && \
    chmod 400 /root/.ssh/* && \
    (ssh -o StrictHostKeyChecking=no -T git@github.com || true) && \
    git clone git@github.com:graphistry/viz-app.git && \
    cd viz-app && \
    bash -l -c "npm install && npm run build && npm version patch && npm publish"

CMD bash -l
