---
- name: Test desired SSH port for connectivity
  become: no
  local_action: shell nc -z -w5 {{ inventory_hostname }} {{ ansible_ssh_port }}
  register: nc_ssh_port
  failed_when: nc_ssh_port.rc != 0
  changed_when: False
  ignore_errors: yes

- name: Set Ansible to temporarily use port 22
  become: no
  set_fact: ansible_ssh_port=22
  when: nc_ssh_port|failed

- name: Set sshd port
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  register: sshd_config
  become: yes
  become_user: root

- name: Finding server IP address, so we can configure hostname
  setup:

- name: Set fully-qualified domain name
  template: src=hosts.j2 dest=/etc/hosts
  become: yes
  become_user: root

- name: Set hostname
  hostname: name="{{ inventory_hostname_short }}"
  become: yes
  become_user: root

- name: Configure Ubuntu cloud-init to use our hostname and not overwrite it
  template: src=50graphistry-hostname.cfg.j2
            dest=/etc/cloud/cloud.cfg.d/50graphistry-hostname.cfg
            owner=root
            group=root
            mode=0644
  become: yes
  become_user: root

# This seems to fail with the latest version of Ansible (v1.9). If that happens, log into the
# machine manually (on port 22) and run `sudo service sshd restart`.
- name: Restart sshd
  service: name=ssh state=reloaded pattern=/usr/sbin/sshd enabled=yes
  when: nc_ssh_port|failed
  become: yes

- name: Set Ansible back to using our custom SSH port
  become: no
  set_fact: ansible_ssh_port={{ graphistry_ssh_port }}
  when: nc_ssh_port|failed
