---
    root: true
    extends: 'eslint:recommended'

    parserOptions:
      ecmaVersion: 2017
      ecmaFeatures:
        impliedStrict: true
        jsx: true
        experimentalObjectRestSpread: true
      sourceType: module

    env:
      es6: true
      commonjs: true
      node: true
      browser: true
      shared-node-browser: true
      mocha: true

    rules:
      strict:
        - error
        - safe
      eqeqeq:
        - error
        - allow-null
      guard-for-in: warn

      no-eval: error
      no-extend-native: error
      no-caller: error
      no-console: off

      no-unused-vars:
        - warn
        - vars: all
          args: after-used
      no-use-before-define:
        - error
        - nofunc
      no-undef: warn
      no-shadow:
        - error
        - hoist: functions

      max-params:
        - warn
        - 7
      max-depth:
        - warn
        - 3
      complexity:
        - warn
        - 11

      linebreak-style:
        - error
        - unix
      indent:
        - error
        - 4
        - SwitchCase: 1
          VariableDeclarator: 1
      no-multi-spaces:
        - warn
        - exceptions:
            VariableDeclarator: true
      quotes:
        - warn
        - 'single'
        - avoidEscape: true
          allowTemplateLiterals: true
      curly:
        - error
        - all
      semi:
        - warn
        - always

      new-cap: warn
      camelcase:
        - warn
        - properties: always
      no-underscore-dangle: off
      no-irregular-whitespace: error
      no-trailing-spaces: error
      wrap-iife:
        - error
        - inside
