# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    # More closely mirror https://github.com/sphinx-doc/sphinx-docker-images
    - graphviz
    - imagemagick
    - make
    - pandoc
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
  commands:

    # setup
    - pip install ".[docs]"
    - ln -s demos docs/source/demos

    # build
    - sphinx-build -b html -d docs/doctrees docs/source $READTHEDOCS_OUTPUT/html/
    - sphinx-build -b epub -d docs/doctrees docs/source $READTHEDOCS_OUTPUT/epub/
    - sphinx-build -b latex -d docs/doctrees docs/source $READTHEDOCS_OUTPUT/pdf/
    - cd $READTHEDOCS_OUTPUT/pdf/ && pdflatex -interaction=nonstopmode PyGraphistry.tex && pdflatex -interaction=nonstopmode PyGraphistry.tex    

#for nav links?
formats:
  - pdf
  - epub
  - htmlzip

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
