# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    # More closely mirror https://github.com/sphinx-doc/sphinx-docker-images
    - graphviz
    - imagemagick
    - make
    - pandoc
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
  commands:

    # setup
    - pip install ".[docs]"
    - cp -r demos docs/source/demos
    - cp README.md docs/source/README.md
    - cp ARCHITECTURE.md docs/source/ARCHITECTURE.md
    - cp CONTRIBUTING.md docs/source/CONTRIBUTING.md
    - cp DEVELOP.md docs/source/DEVELOP.md

    # build html
    - sphinx-build -b html -d docs/doctrees docs/source $READTHEDOCS_OUTPUT/html/

    # build epub
    - sphinx-build -b epub -d docs/doctrees docs/source docs/_build/latexpdf
    - mkdir -p $READTHEDOCS_OUTPUT/epub
    - cp docs/_build/latexpdf/PyGraphistry.epub $READTHEDOCS_OUTPUT/epub/PyGraphistry.epub

    # build pdf - run pdflatex 3 times to resolve cross-references
    # Use || true because pdflatex returns non-zero for warnings (not just errors)
    - sphinx-build -b latex -d docs/doctrees docs/source docs/_build/latexpdf
    - cd docs/_build/latexpdf && pdflatex -file-line-error -interaction=nonstopmode PyGraphistry.tex || true
    - cd docs/_build/latexpdf && pdflatex -file-line-error -interaction=nonstopmode PyGraphistry.tex || true
    - cd docs/_build/latexpdf && pdflatex -file-line-error -interaction=nonstopmode PyGraphistry.tex || true
    - mkdir -p $READTHEDOCS_OUTPUT/pdf
    - cp docs/_build/latexpdf/PyGraphistry.pdf $READTHEDOCS_OUTPUT/pdf/PyGraphistry.pdf

#for nav links?
formats:
  - pdf
  - epub
  - htmlzip

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
