version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py


formats:
  - pdf
  - htmlzip
  - epub

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: dev 