# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - pandoc
  commands:
    - pip install ".[docs]"
    - ln -s ../../demos docs/source/demos
    - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html
    - sphinx-build -b epub docs/source $READTHEDOCS_OUTPUT/epub
    - sphinx-build -b htmlzip docs/source $READTHEDOCS_OUTPUT/htmlzip

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
