FROM graphistry/baseapp:1.2

# fetch secrets from our vault, do the npm installs, and delete the secrets.
ARG BUILD_NUMBER
ENV APPDIR /app
WORKDIR $APPDIR

COPY . $APPDIR


RUN mkdir /root/.ssh && \
    curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/github/id_rsa > /root/.ssh/id_rsa && \
    curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/github/id_rsa.pub > /root/.ssh/id_rsa.pub && \
    curl $(/sbin/ip route | awk '/default/ {print $3}'):17290/npm/rc > /root/.npmrc && \
    chmod 400 /root/.ssh/* && \
    md5sum /root/.ssh/* && \
    (ssh -o StrictHostKeyChecking=no -T git@github.com || true) && \
    cd $APPDIR && \
    bash -l -c "npm install" && \
    npm run build ; \
    cd $APPDIR/packages/viz-app && \
    npm run build && \
    cd $APPDIR/packages/api-client && \
    npm run build && \
    cd $APPDIR && \
    yes | ./node_modules/.bin/lerna publish --yes && \
    shred -u /root/.ssh/* /root/.npmrc
