FROM graphistry/baseapp:1.2

# fetch secrets from our vault, do the npm installs & publish, and delete the secrets.
ARG BUILD_NUMBER
ENV APPDIR /app
WORKDIR $APPDIR

COPY ./wholly-innocuous/files/npm/rc /root/.npmrc

COPY . .

RUN bash -l -c "npm install"
RUN bash -l -c "npm run build"
RUN ./node_modules/.bin/lerna publish --skip-git --skip-npm --force-publish=* --repo-version=`node -e "console.log(JSON.parse(fs.readFileSync('./lerna.json')).version.replace(/[.]\d+$/,'.$BUILD_NUMBER'))"` --yes

WORKDIR $APPDIR/packages/viz-app
RUN npm run build

WORKDIR $APPDIR/packages/viz-app-client-api
RUN npm run build

WORKDIR $APPDIR
RUN ./node_modules/.bin/lerna publish --skip-git --force-publish=* --repo-version=`node -e "console.log(JSON.parse(fs.readFileSync('./lerna.json')).version.replace(/[.]\d+$/,'.$BUILD_NUMBER'))"` --yes
