---
- name: Reboot server
  command: shutdown -r now "Ansible updates triggered"
  sudo: yes
  async: 0
  poll: 0
  ignore_errors: true
  # when: cuda_installed.changed
  # tags: provision

- name: Wait for server to restart
  local_action: wait_for host={{ inventory_hostname }}
                state=started
                port={{ ansible_ssh_port }}
                delay=30
  # when: cuda_installed.changed
  sudo: false
