from graphistry.compute import e_forward, e_undirected, n

from tests.cypher_tck.models import Expected, GraphFixture, Scenario
from tests.cypher_tck.parse_cypher import graph_fixture_from_create

from tests.cypher_tck.scenarios.fixtures import (
    MATCH5_GRAPH,
    MATCH7_GRAPH_SINGLE,
    MATCH7_GRAPH_AB,
    MATCH7_GRAPH_ABC,
    MATCH7_GRAPH_REL,
    MATCH7_GRAPH_X,
    MATCH7_GRAPH_AB_X,
    MATCH7_GRAPH_LABELS,
    MATCH7_GRAPH_PLAYER_TEAM_BOTH,
    MATCH7_GRAPH_PLAYER_TEAM_SINGLE,
    MATCH7_GRAPH_PLAYER_TEAM_DIFF,
    WITH_ORDERBY4_GRAPH,
    BINARY_TREE_1_GRAPH,
    BINARY_TREE_2_GRAPH,
)


SCENARIOS = [
    Scenario(
        key='expr-boolean2-1',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[1] Disjunction of two truth values',
        cypher='RETURN true OR true AS tt,\n             true OR false AS tf,\n             true OR null AS tn,\n             false OR true AS ft,\n             false OR false AS ff,\n             false OR null AS fn,\n             null OR true AS nt,\n             null OR false AS nf,\n             null OR null AS nn',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'tt': 'true', 'tf': 'true', 'tn': 'true', 'ft': 'true', 'ff': 'false', 'fn': 'null', 'nt': 'true', 'nf': 'null', 'nn': 'null'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-2',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[2] Disjunction of three truth values',
        cypher='RETURN true OR true OR true AS ttt,\n             true OR true OR false AS ttf,\n             true OR true OR null AS ttn,\n             true OR false OR true AS tft,\n             true OR false OR false AS tff,\n             true OR false OR null AS tfn,\n             true OR null OR true AS tnt,\n             true OR null OR false AS tnf,\n             true OR null OR null AS tnn,\n             false OR true OR true AS ftt,\n             false OR true OR false AS ftf,\n             false OR true OR null AS ftn,\n             false OR false OR true AS fft,\n             false OR false OR false AS fff,\n             false OR false OR null AS ffn,\n             false OR null OR true AS fnt,\n             false OR null OR false AS fnf,\n             false OR null OR null AS fnn,\n             null OR true OR true AS ntt,\n             null OR true OR false AS ntf,\n             null OR true OR null AS ntn,\n             null OR false OR true AS nft,\n             null OR false OR false AS nff,\n             null OR false OR null AS nfn,\n             null OR null OR true AS nnt,\n             null OR null OR false AS nnf,\n             null OR null OR null AS nnn',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'ttt': 'true', 'ttf': 'true', 'ttn': 'true', 'tft': 'true', 'tff': 'true', 'tfn': 'true', 'tnt': 'true', 'tnf': 'true', 'tnn': 'true', 'ftt': 'true', 'ftf': 'true', 'ftn': 'true', 'fft': 'true', 'fff': 'false', 'ffn': 'null', 'fnt': 'true', 'fnf': 'null', 'fnn': 'null', 'ntt': 'true', 'ntf': 'true', 'ntn': 'true', 'nft': 'true', 'nff': 'null', 'nfn': 'null', 'nnt': 'true', 'nnf': 'null', 'nnn': 'null'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-3',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[3] Disjunction of many truth values',
        cypher='RETURN true OR true OR true OR true OR true OR true OR true OR true OR true OR true OR true AS t,\n             true OR true OR true OR false OR true OR true OR true OR true OR true OR true OR true AS tsf,\n             true OR true OR true OR null OR true OR true OR true OR true OR true OR true OR true AS tsn,\n             false OR false OR false OR false OR false OR false OR false OR false OR false OR false OR false AS f,\n             false OR false OR false OR false OR true OR false OR false OR false OR false OR false OR false AS fst,\n             false OR false OR false OR false OR false OR false OR null OR false OR false OR false OR false AS fsn,\n             null OR null OR null OR null OR null OR null OR null OR null OR null OR null OR null AS n,\n             null OR null OR null OR null OR true OR null OR null OR null OR null OR null OR null AS nst,\n             null OR null OR null OR null OR false OR null OR null OR null OR null OR null OR null AS nsf,\n             true OR false OR false OR false OR true OR false OR false OR true OR true OR true OR false AS m1,\n             true OR true OR false OR false OR true OR false OR false OR true OR true OR true OR false AS m2,\n             true OR true OR false OR false OR true OR null OR false OR true OR true OR null OR false AS m3',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'t': 'true', 'tsf': 'true', 'tsn': 'true', 'f': 'false', 'fst': 'true', 'fsn': 'null', 'n': 'null', 'nst': 'true', 'nsf': 'null', 'm1': 'true', 'm2': 'true', 'm3': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-4',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[4] Disjunction is commutative on non-null',
        cypher='UNWIND [true, false] AS a\n      UNWIND [true, false] AS b\n      RETURN a, b, (a OR b) = (b OR a) AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-5',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[5] Disjunction is commutative on null',
        cypher='UNWIND [true, false, null] AS a\n      UNWIND [true, false, null] AS b\n      WITH a, b WHERE a IS NULL OR b IS NULL\n      RETURN a, b, (a OR b) IS NULL = (b OR a) IS NULL AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-6',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[6] Disjunction is associative on non-null',
        cypher='UNWIND [true, false] AS a\n      UNWIND [true, false] AS b\n      UNWIND [true, false] AS c\n      RETURN a, b, c, (a OR (b OR c)) = ((a OR b) OR c) AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'true', 'c': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'true', 'c': 'false', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'c': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'c': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'c': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'c': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'c': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'c': 'false', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-7',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[7] Disjunction is associative on null',
        cypher='UNWIND [true, false, null] AS a\n      UNWIND [true, false, null] AS b\n      UNWIND [true, false, null] AS c\n      WITH a, b, c WHERE a IS NULL OR b IS NULL OR c IS NULL\n      RETURN a, b, c, (a OR (b OR c)) IS NULL = ((a OR b) OR c) IS NULL AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'true', 'c': 'null', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'c': 'null', 'result': 'true'},
            {'a': 'true', 'b': 'null', 'c': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'null', 'c': 'false', 'result': 'true'},
            {'a': 'true', 'b': 'null', 'c': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'c': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'c': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'c': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'c': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'c': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'c': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'c': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'c': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'c': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'c': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'c': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'c': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'c': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'c': 'null', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-1',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 1)',
        cypher='RETURN 123 OR true',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-2',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 2)',
        cypher='RETURN 123.4 OR false',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-3',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 3)',
        cypher='RETURN 123.4 OR null',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-4',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 4)',
        cypher="RETURN 'foo' OR true",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-5',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 5)',
        cypher='RETURN [] OR false',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-6',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 6)',
        cypher='RETURN [true] OR false',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-7',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 7)',
        cypher='RETURN [null] OR null',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-8',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 8)',
        cypher='RETURN {} OR true',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-9',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 9)',
        cypher='RETURN {x: []} OR true',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-10',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 10)',
        cypher='RETURN false OR 123',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-11',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 11)',
        cypher='RETURN true OR 123.4',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-12',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 12)',
        cypher="RETURN false OR 'foo'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-13',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 13)',
        cypher="RETURN null OR 'foo'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-14',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 14)',
        cypher='RETURN true OR []',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-15',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 15)',
        cypher='RETURN true OR [false]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-16',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 16)',
        cypher='RETURN null OR [null]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-17',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 17)',
        cypher='RETURN false OR {}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-18',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 18)',
        cypher='RETURN false OR {x: []}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-19',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 19)',
        cypher="RETURN 123 OR 'foo'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-20',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 20)',
        cypher='RETURN 123.4 OR 123.4',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-21',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 21)',
        cypher="RETURN 'foo' OR {x: []}",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-22',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 22)',
        cypher='RETURN [true] OR [true]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean2-8-23',
        feature_path='tck/features/expressions/boolean/Boolean2.feature',
        scenario='[8] Fail on disjunction of at least one non-booleans (example 23)',
        cypher='RETURN {x: []} OR [123]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),
]
