from graphistry.compute import e_forward, e_undirected, n

from tests.cypher_tck.models import Expected, GraphFixture, Scenario
from tests.cypher_tck.parse_cypher import graph_fixture_from_create

from tests.cypher_tck.scenarios.fixtures import (
    MATCH5_GRAPH,
    MATCH7_GRAPH_SINGLE,
    MATCH7_GRAPH_AB,
    MATCH7_GRAPH_ABC,
    MATCH7_GRAPH_REL,
    MATCH7_GRAPH_X,
    MATCH7_GRAPH_AB_X,
    MATCH7_GRAPH_LABELS,
    MATCH7_GRAPH_PLAYER_TEAM_BOTH,
    MATCH7_GRAPH_PLAYER_TEAM_SINGLE,
    MATCH7_GRAPH_PLAYER_TEAM_DIFF,
    WITH_ORDERBY4_GRAPH,
    BINARY_TREE_1_GRAPH,
    BINARY_TREE_2_GRAPH,
)


SCENARIOS = [
    Scenario(
        key='expr-boolean4-1',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[1] Logical negation of truth values',
        cypher='RETURN NOT true AS nt, NOT false AS nf, NOT null AS nn',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'nt': 'false', 'nf': 'true', 'nn': 'null'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-2',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[2] Double logical negation of truth values',
        cypher='RETURN NOT NOT true AS nnt, NOT NOT false AS nnf, NOT NOT null AS nnn',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'nnt': 'true', 'nnf': 'false', 'nnn': 'null'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-3',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[3] NOT and false',
        cypher="MATCH (n)\n      WHERE NOT(n.name = 'apa' AND false)\n      RETURN n",
        graph=graph_fixture_from_create(
            """
            CREATE ({name: 'a'})
            """
        ),
        expected=Expected(
            rows=[
            {'n': "({name: 'a'})"}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-1',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 1)',
        cypher='RETURN NOT 0',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-2',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 2)',
        cypher='RETURN NOT 1',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-3',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 3)',
        cypher='RETURN NOT 123',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-4',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 4)',
        cypher='RETURN NOT 123.4',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-5',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 5)',
        cypher="RETURN NOT ''",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-6',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 6)',
        cypher="RETURN NOT 'false'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-7',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 7)',
        cypher="RETURN NOT 'true'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-8',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 8)',
        cypher="RETURN NOT 'foo'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-9',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 9)',
        cypher='RETURN NOT []',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-10',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 10)',
        cypher='RETURN NOT [null]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-11',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 11)',
        cypher='RETURN NOT [true]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-12',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 12)',
        cypher='RETURN NOT [false]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-13',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 13)',
        cypher='RETURN NOT [true, false]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-14',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 14)',
        cypher='RETURN NOT [false, true]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-15',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 15)',
        cypher='RETURN NOT [0]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-16',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 16)',
        cypher='RETURN NOT [1]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-17',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 17)',
        cypher='RETURN NOT [1, 2, 3]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-18',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 18)',
        cypher='RETURN NOT [0.0]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-19',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 19)',
        cypher='RETURN NOT [1.0]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-20',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 20)',
        cypher='RETURN NOT [1.0, 2.1]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-21',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 21)',
        cypher="RETURN NOT ['']",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-22',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 22)',
        cypher="RETURN NOT ['', '']",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-23',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 23)',
        cypher="RETURN NOT ['true']",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-24',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 24)',
        cypher="RETURN NOT ['false']",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-25',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 25)',
        cypher="RETURN NOT ['a', 'b']",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-26',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 26)',
        cypher='RETURN NOT {}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-27',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 27)',
        cypher='RETURN NOT {``: null}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-28',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 28)',
        cypher='RETURN NOT {a: null}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-29',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 29)',
        cypher='RETURN NOT {``: true}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-30',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 30)',
        cypher='RETURN NOT {``: false}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-31',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 31)',
        cypher='RETURN NOT {true: true}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-32',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 32)',
        cypher='RETURN NOT {false: false}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-33',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 33)',
        cypher='RETURN NOT {bool: true}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-34',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 34)',
        cypher='RETURN NOT {bool: false}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-35',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 35)',
        cypher='RETURN NOT {``: 0}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-36',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 36)',
        cypher='RETURN NOT {``: 1}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-37',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 37)',
        cypher='RETURN NOT {a: 0}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-38',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 38)',
        cypher='RETURN NOT {a: 1}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-39',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 39)',
        cypher='RETURN NOT {a: 1, b: 2}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-40',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 40)',
        cypher='RETURN NOT {``: 0.0}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-41',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 41)',
        cypher='RETURN NOT {``: 1.0}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-42',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 42)',
        cypher='RETURN NOT {a: 0.0}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-43',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 43)',
        cypher='RETURN NOT {a: 1.0}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-44',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 44)',
        cypher='RETURN NOT {a: 1.0, b: 2.1}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-45',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 45)',
        cypher="RETURN NOT {``: ''}",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-46',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 46)',
        cypher="RETURN NOT {a: ''}",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-47',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 47)',
        cypher="RETURN NOT {a: 'a'}",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-48',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 48)',
        cypher="RETURN NOT {a: 'a', b: 'b'}",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean4-4-49',
        feature_path='tck/features/expressions/boolean/Boolean4.feature',
        scenario='[4] Fail when using NOT on a non-boolean literal (example 49)',
        cypher='RETURN NOT {a: 12, b: true}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),
]
