from graphistry.compute import e_forward, e_undirected, n

from tests.cypher_tck.models import Expected, GraphFixture, Scenario
from tests.cypher_tck.parse_cypher import graph_fixture_from_create

from tests.cypher_tck.scenarios.fixtures import (
    MATCH5_GRAPH,
    MATCH7_GRAPH_SINGLE,
    MATCH7_GRAPH_AB,
    MATCH7_GRAPH_ABC,
    MATCH7_GRAPH_REL,
    MATCH7_GRAPH_X,
    MATCH7_GRAPH_AB_X,
    MATCH7_GRAPH_LABELS,
    MATCH7_GRAPH_PLAYER_TEAM_BOTH,
    MATCH7_GRAPH_PLAYER_TEAM_SINGLE,
    MATCH7_GRAPH_PLAYER_TEAM_DIFF,
    WITH_ORDERBY4_GRAPH,
    BINARY_TREE_1_GRAPH,
    BINARY_TREE_2_GRAPH,
)


SCENARIOS = [
    Scenario(
        key='expr-boolean1-1',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[1] Conjunction of two truth values',
        cypher='RETURN true AND true AS tt,\n             true AND false AS tf,\n             true AND null AS tn,\n             false AND true AS ft,\n             false AND false AS ff,\n             false AND null AS fn,\n             null AND true AS nt,\n             null AND false AS nf,\n             null AND null AS nn',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'tt': 'true', 'tf': 'false', 'tn': 'null', 'ft': 'false', 'ff': 'false', 'fn': 'false', 'nt': 'null', 'nf': 'false', 'nn': 'null'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-2',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[2] Conjunction of three truth values',
        cypher='RETURN true AND true AND true AS ttt,\n             true AND true AND false AS ttf,\n             true AND true AND null AS ttn,\n             true AND false AND true AS tft,\n             true AND false AND false AS tff,\n             true AND false AND null AS tfn,\n             true AND null AND true AS tnt,\n             true AND null AND false AS tnf,\n             true AND null AND null AS tnn,\n             false AND true AND true AS ftt,\n             false AND true AND false AS ftf,\n             false AND true AND null AS ftn,\n             false AND false AND true AS fft,\n             false AND false AND false AS fff,\n             false AND false AND null AS ffn,\n             false AND null AND true AS fnt,\n             false AND null AND false AS fnf,\n             false AND null AND null AS fnn,\n             null AND true AND true AS ntt,\n             null AND true AND false AS ntf,\n             null AND true AND null AS ntn,\n             null AND false AND true AS nft,\n             null AND false AND false AS nff,\n             null AND false AND null AS nfn,\n             null AND null AND true AS nnt,\n             null AND null AND false AS nnf,\n             null AND null AND null AS nnn',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'ttt': 'true', 'ttf': 'false', 'ttn': 'null', 'tft': 'false', 'tff': 'false', 'tfn': 'false', 'tnt': 'null', 'tnf': 'false', 'tnn': 'null', 'ftt': 'false', 'ftf': 'false', 'ftn': 'false', 'fft': 'false', 'fff': 'false', 'ffn': 'false', 'fnt': 'false', 'fnf': 'false', 'fnn': 'false', 'ntt': 'null', 'ntf': 'false', 'ntn': 'null', 'nft': 'false', 'nff': 'false', 'nfn': 'false', 'nnt': 'null', 'nnf': 'false', 'nnn': 'null'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-3',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[3] Conjunction of many truth values',
        cypher='RETURN true AND true AND true AND true AND true AND true AND true AND true AND true AND true AND true AS t,\n             true AND true AND true AND false AND true AND true AND true AND true AND true AND true AND true AS tsf,\n             true AND true AND true AND null AND true AND true AND true AND true AND true AND true AND true AS tsn,\n             false AND false AND false AND false AND false AND false AND false AND false AND false AND false AND false AS f,\n             false AND false AND false AND false AND true AND false AND false AND false AND false AND false AND false AS fst,\n             false AND false AND false AND false AND false AND false AND null AND false AND false AND false AND false AS fsn,\n             null AND null AND null AND null AND null AND null AND null AND null AND null AND null AND null AS n,\n             null AND null AND null AND null AND true AND null AND null AND null AND null AND null AND null AS nst,\n             null AND null AND null AND null AND false AND null AND null AND null AND null AND null AND null AS nsf,\n             true AND false AND false AND false AND true AND false AND false AND true AND true AND true AND false AS m1,\n             true AND true AND false AND false AND true AND false AND false AND true AND true AND true AND false AS m2,\n             true AND true AND false AND false AND true AND null AND false AND true AND true AND null AND false AS m3',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'t': 'true', 'tsf': 'false', 'tsn': 'null', 'f': 'false', 'fst': 'false', 'fsn': 'false', 'n': 'null', 'nst': 'null', 'nsf': 'false', 'm1': 'false', 'm2': 'false', 'm3': 'false'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-4',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[4] Conjunction is commutative on non-null',
        cypher='UNWIND [true, false] AS a\n      UNWIND [true, false] AS b\n      RETURN a, b, (a AND b) = (b AND a) AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-5',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[5] Conjunction is commutative on null',
        cypher='UNWIND [true, false, null] AS a\n      UNWIND [true, false, null] AS b\n      WITH a, b WHERE a IS NULL OR b IS NULL\n      RETURN a, b, (a AND b) IS NULL = (b AND a) IS NULL AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-6',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[6] Conjunction is associative on non-null',
        cypher='UNWIND [true, false] AS a\n      UNWIND [true, false] AS b\n      UNWIND [true, false] AS c\n      RETURN a, b, c, (a AND (b AND c)) = ((a AND b) AND c) AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'true', 'c': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'true', 'c': 'false', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'c': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'c': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'c': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'c': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'c': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'c': 'false', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-7',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[7] Conjunction is associative on null',
        cypher='UNWIND [true, false, null] AS a\n      UNWIND [true, false, null] AS b\n      UNWIND [true, false, null] AS c\n      WITH a, b, c WHERE a IS NULL OR b IS NULL OR c IS NULL\n      RETURN a, b, c, (a AND (b AND c)) IS NULL = ((a AND b) AND c) IS NULL AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'true', 'c': 'null', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'c': 'null', 'result': 'true'},
            {'a': 'true', 'b': 'null', 'c': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'null', 'c': 'false', 'result': 'true'},
            {'a': 'true', 'b': 'null', 'c': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'c': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'c': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'c': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'c': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'c': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'c': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'c': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'c': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'c': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'c': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'c': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'c': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'c': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'c': 'null', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-1',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 1)',
        cypher='RETURN 123 AND true',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-2',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 2)',
        cypher='RETURN 123.4 AND false',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-3',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 3)',
        cypher='RETURN 123.4 AND null',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-4',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 4)',
        cypher="RETURN 'foo' AND true",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-5',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 5)',
        cypher='RETURN [] AND false',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-6',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 6)',
        cypher='RETURN [true] AND false',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-7',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 7)',
        cypher='RETURN [null] AND null',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-8',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 8)',
        cypher='RETURN {} AND true',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-9',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 9)',
        cypher='RETURN {x: []} AND true',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-10',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 10)',
        cypher='RETURN false AND 123',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-11',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 11)',
        cypher='RETURN true AND 123.4',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-12',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 12)',
        cypher="RETURN false AND 'foo'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-13',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 13)',
        cypher="RETURN null AND 'foo'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-14',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 14)',
        cypher='RETURN true AND []',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-15',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 15)',
        cypher='RETURN true AND [false]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-16',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 16)',
        cypher='RETURN null AND [null]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-17',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 17)',
        cypher='RETURN false AND {}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-18',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 18)',
        cypher='RETURN false AND {x: []}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-19',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 19)',
        cypher="RETURN 123 AND 'foo'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-20',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 20)',
        cypher='RETURN 123.4 AND 123.4',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-21',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 21)',
        cypher="RETURN 'foo' AND {x: []}",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-22',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 22)',
        cypher='RETURN [true] AND [true]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean1-8-23',
        feature_path='tck/features/expressions/boolean/Boolean1.feature',
        scenario='[8] Fail on conjunction of at least one non-booleans (example 23)',
        cypher='RETURN {x: []} AND [123]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),
]
