from graphistry.compute import e_forward, e_undirected, n

from tests.cypher_tck.models import Expected, GraphFixture, Scenario
from tests.cypher_tck.parse_cypher import graph_fixture_from_create

from tests.cypher_tck.scenarios.fixtures import (
    MATCH5_GRAPH,
    MATCH7_GRAPH_SINGLE,
    MATCH7_GRAPH_AB,
    MATCH7_GRAPH_ABC,
    MATCH7_GRAPH_REL,
    MATCH7_GRAPH_X,
    MATCH7_GRAPH_AB_X,
    MATCH7_GRAPH_LABELS,
    MATCH7_GRAPH_PLAYER_TEAM_BOTH,
    MATCH7_GRAPH_PLAYER_TEAM_SINGLE,
    MATCH7_GRAPH_PLAYER_TEAM_DIFF,
    WITH_ORDERBY4_GRAPH,
    BINARY_TREE_1_GRAPH,
    BINARY_TREE_2_GRAPH,
)


SCENARIOS = [
    Scenario(
        key='expr-boolean3-1',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[1] Exclusive disjunction of two truth values',
        cypher='RETURN true XOR true AS tt,\n             true XOR false AS tf,\n             true XOR null AS tn,\n             false XOR true AS ft,\n             false XOR false AS ff,\n             false XOR null AS fn,\n             null XOR true AS nt,\n             null XOR false AS nf,\n             null XOR null AS nn',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'tt': 'false', 'tf': 'true', 'tn': 'null', 'ft': 'true', 'ff': 'false', 'fn': 'null', 'nt': 'null', 'nf': 'null', 'nn': 'null'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-2',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[2] Exclusive disjunction of three truth values',
        cypher='RETURN true XOR true XOR true AS ttt,\n             true XOR true XOR false AS ttf,\n             true XOR true XOR null AS ttn,\n             true XOR false XOR true AS tft,\n             true XOR false XOR false AS tff,\n             true XOR false XOR null AS tfn,\n             true XOR null XOR true AS tnt,\n             true XOR null XOR false AS tnf,\n             true XOR null XOR null AS tnn,\n             false XOR true XOR true AS ftt,\n             false XOR true XOR false AS ftf,\n             false XOR true XOR null AS ftn,\n             false XOR false XOR true AS fft,\n             false XOR false XOR false AS fff,\n             false XOR false XOR null AS ffn,\n             false XOR null XOR true AS fnt,\n             false XOR null XOR false AS fnf,\n             false XOR null XOR null AS fnn,\n             null XOR true XOR true AS ntt,\n             null XOR true XOR false AS ntf,\n             null XOR true XOR null AS ntn,\n             null XOR false XOR true AS nft,\n             null XOR false XOR false AS nff,\n             null XOR false XOR null AS nfn,\n             null XOR null XOR true AS nnt,\n             null XOR null XOR false AS nnf,\n             null XOR null XOR null AS nnn',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'ttt': 'true', 'ttf': 'false', 'ttn': 'null', 'tft': 'false', 'tff': 'true', 'tfn': 'null', 'tnt': 'null', 'tnf': 'null', 'tnn': 'null', 'ftt': 'false', 'ftf': 'true', 'ftn': 'null', 'fft': 'true', 'fff': 'false', 'ffn': 'null', 'fnt': 'null', 'fnf': 'null', 'fnn': 'null', 'ntt': 'null', 'ntf': 'null', 'ntn': 'null', 'nft': 'null', 'nff': 'null', 'nfn': 'null', 'nnt': 'null', 'nnf': 'null', 'nnn': 'null'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-3',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[3] Exclusive disjunction of many truth values',
        cypher='RETURN true XOR true XOR true XOR true XOR true XOR true XOR true XOR true XOR true XOR true XOR true AS t,\n             true XOR true XOR true XOR false XOR true XOR true XOR true XOR true XOR true XOR true XOR true AS tsf,\n             true XOR true XOR true XOR null XOR true XOR true XOR true XOR true XOR true XOR true XOR true AS tsn,\n             false XOR false XOR false XOR false XOR false XOR false XOR false XOR false XOR false XOR false XOR false AS f,\n             false XOR false XOR false XOR false XOR true XOR false XOR false XOR false XOR false XOR false XOR false AS fst,\n             false XOR false XOR false XOR false XOR false XOR false XOR null XOR false XOR false XOR false XOR false AS fsn,\n             null XOR null XOR null XOR null XOR null XOR null XOR null XOR null XOR null XOR null XOR null AS n,\n             null XOR null XOR null XOR null XOR true XOR null XOR null XOR null XOR null XOR null XOR null AS nst,\n             null XOR null XOR null XOR null XOR false XOR null XOR null XOR null XOR null XOR null XOR null AS nsf,\n             true XOR false XOR false XOR false XOR true XOR false XOR false XOR true XOR true XOR true XOR false AS m1,\n             true XOR true XOR false XOR false XOR true XOR false XOR false XOR true XOR true XOR true XOR false AS m2,\n             true XOR true XOR false XOR false XOR true XOR null XOR false XOR true XOR true XOR null XOR false AS m3',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'t': 'true', 'tsf': 'false', 'tsn': 'null', 'f': 'false', 'fst': 'true', 'fsn': 'null', 'n': 'null', 'nst': 'null', 'nsf': 'null', 'm1': 'true', 'm2': 'false', 'm3': 'null'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-4',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[4] Exclusive disjunction is commutative on non-null',
        cypher='UNWIND [true, false] AS a\n      UNWIND [true, false] AS b\n      RETURN a, b, (a XOR b) = (b XOR a) AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-5',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[5] Exclusive disjunction is commutative on null',
        cypher='UNWIND [true, false, null] AS a\n      UNWIND [true, false, null] AS b\n      WITH a, b WHERE a IS NULL OR b IS NULL\n      RETURN a, b, (a XOR b) IS NULL = (b XOR a) IS NULL AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-6',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[6] Exclusive disjunction is associative on non-null',
        cypher='UNWIND [true, false] AS a\n      UNWIND [true, false] AS b\n      UNWIND [true, false] AS c\n      RETURN a, b, c, (a XOR (b XOR c)) = ((a XOR b) XOR c) AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'true', 'c': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'true', 'c': 'false', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'c': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'c': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'c': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'c': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'c': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'c': 'false', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-7',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[7] Exclusive disjunction is associative on null',
        cypher='UNWIND [true, false, null] AS a\n      UNWIND [true, false, null] AS b\n      UNWIND [true, false, null] AS c\n      WITH a, b, c WHERE a IS NULL OR b IS NULL OR c IS NULL\n      RETURN a, b, c, (a XOR (b XOR c)) IS NULL = ((a XOR b) XOR c) IS NULL AS result',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(
            rows=[
            {'a': 'true', 'b': 'true', 'c': 'null', 'result': 'true'},
            {'a': 'true', 'b': 'false', 'c': 'null', 'result': 'true'},
            {'a': 'true', 'b': 'null', 'c': 'true', 'result': 'true'},
            {'a': 'true', 'b': 'null', 'c': 'false', 'result': 'true'},
            {'a': 'true', 'b': 'null', 'c': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'true', 'c': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'false', 'c': 'null', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'c': 'true', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'c': 'false', 'result': 'true'},
            {'a': 'false', 'b': 'null', 'c': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'c': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'c': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'true', 'c': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'c': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'c': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'false', 'c': 'null', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'c': 'true', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'c': 'false', 'result': 'true'},
            {'a': 'null', 'b': 'null', 'c': 'null', 'result': 'true'}
            ],
        ),
        gfql=None,
        status="xfail",
        reason='Expression evaluation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-1',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 1)',
        cypher='RETURN 123 XOR true',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-2',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 2)',
        cypher='RETURN 123.4 XOR false',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-3',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 3)',
        cypher='RETURN 123.4 XOR null',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-4',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 4)',
        cypher="RETURN 'foo' XOR true",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-5',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 5)',
        cypher='RETURN [] XOR false',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-6',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 6)',
        cypher='RETURN [true] XOR false',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-7',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 7)',
        cypher='RETURN [null] XOR null',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-8',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 8)',
        cypher='RETURN {} XOR true',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-9',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 9)',
        cypher='RETURN {x: []} XOR true',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-10',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 10)',
        cypher='RETURN false XOR 123',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-11',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 11)',
        cypher='RETURN true XOR 123.4',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-12',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 12)',
        cypher="RETURN false XOR 'foo'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-13',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 13)',
        cypher="RETURN null XOR 'foo'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-14',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 14)',
        cypher='RETURN true XOR []',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-15',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 15)',
        cypher='RETURN true XOR [false]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-16',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 16)',
        cypher='RETURN null XOR [null]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-17',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 17)',
        cypher='RETURN false XOR {}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-18',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 18)',
        cypher='RETURN false XOR {x: []}',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-19',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 19)',
        cypher="RETURN 123 XOR 'foo'",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-20',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 20)',
        cypher='RETURN 123.4 XOR 123.4',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-21',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 21)',
        cypher="RETURN 'foo' XOR {x: []}",
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-22',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 22)',
        cypher='RETURN [true] XOR [true]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),

    Scenario(
        key='expr-boolean3-8-23',
        feature_path='tck/features/expressions/boolean/Boolean3.feature',
        scenario='[8] Fail on exclusive disjunction of at least one non-booleans (example 23)',
        cypher='RETURN {x: []} XOR [123]',
        graph=GraphFixture(nodes=[], edges=[]),
        expected=Expected(),
        gfql=None,
        status="xfail",
        reason='Compile-time validation is not supported',
        tags=('expr', 'boolean', 'meta-xfail', 'syntax-error', 'xfail'),
    ),
]
