# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph_vector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph_vector.proto',
  package='',
  serialized_pb=_b('\n\x12graph_vector.proto\"\xaf\x06\n\x0bVectorGraph\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12$\n\x04type\x18\x03 \x02(\x0e\x32\x16.VectorGraph.GraphType\x12\x11\n\tnvertices\x18\x04 \x02(\r\x12\x0e\n\x06nedges\x18\x05 \x02(\r\x12 \n\x05\x65\x64ges\x18\x06 \x03(\x0b\x32\x11.VectorGraph.Edge\x12\x38\n\rint32_vectors\x18\x07 \x03(\x0b\x32!.VectorGraph.Int32AttributeVector\x12:\n\x0e\x64ouble_vectors\x18\x08 \x03(\x0b\x32\".VectorGraph.DoubleAttributeVector\x12:\n\x0estring_vectors\x18\t \x03(\x0b\x32\".VectorGraph.StringAttributeVector\x1a \n\x04\x45\x64ge\x12\x0b\n\x03src\x18\x01 \x02(\r\x12\x0b\n\x03\x64st\x18\x02 \x02(\r\x1a\x66\n\x14Int32AttributeVector\x12\x0c\n\x04name\x18\x01 \x02(\t\x12,\n\x06target\x18\x02 \x02(\x0e\x32\x1c.VectorGraph.AttributeTarget\x12\x12\n\x06values\x18\x03 \x03(\rB\x02\x10\x01\x1a\x38\n\x14\x46loatAttributeVector\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x12\n\x06values\x18\x02 \x03(\x02\x42\x02\x10\x01\x1ag\n\x15\x44oubleAttributeVector\x12\x0c\n\x04name\x18\x01 \x02(\t\x12,\n\x06target\x18\x02 \x02(\x0e\x32\x1c.VectorGraph.AttributeTarget\x12\x12\n\x06values\x18\x03 \x03(\x01\x42\x02\x10\x01\x1a\x63\n\x15StringAttributeVector\x12\x0c\n\x04name\x18\x01 \x02(\t\x12,\n\x06target\x18\x02 \x02(\x0e\x32\x1c.VectorGraph.AttributeTarget\x12\x0e\n\x06values\x18\x03 \x03(\t\")\n\tGraphType\x12\x0e\n\nUNDIRECTED\x10\x00\x12\x0c\n\x08\x44IRECTED\x10\x01\"\'\n\x0f\x41ttributeTarget\x12\n\n\x06VERTEX\x10\x00\x12\x08\n\x04\x45\x44GE\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_VECTORGRAPH_GRAPHTYPE = _descriptor.EnumDescriptor(
  name='GraphType',
  full_name='VectorGraph.GraphType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDIRECTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIRECTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=756,
  serialized_end=797,
)
_sym_db.RegisterEnumDescriptor(_VECTORGRAPH_GRAPHTYPE)

_VECTORGRAPH_ATTRIBUTETARGET = _descriptor.EnumDescriptor(
  name='AttributeTarget',
  full_name='VectorGraph.AttributeTarget',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VERTEX', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EDGE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=799,
  serialized_end=838,
)
_sym_db.RegisterEnumDescriptor(_VECTORGRAPH_ATTRIBUTETARGET)


_VECTORGRAPH_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='VectorGraph.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='VectorGraph.Edge.src', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dst', full_name='VectorGraph.Edge.dst', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=386,
)

_VECTORGRAPH_INT32ATTRIBUTEVECTOR = _descriptor.Descriptor(
  name='Int32AttributeVector',
  full_name='VectorGraph.Int32AttributeVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='VectorGraph.Int32AttributeVector.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='VectorGraph.Int32AttributeVector.target', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='VectorGraph.Int32AttributeVector.values', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=490,
)

_VECTORGRAPH_FLOATATTRIBUTEVECTOR = _descriptor.Descriptor(
  name='FloatAttributeVector',
  full_name='VectorGraph.FloatAttributeVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='VectorGraph.FloatAttributeVector.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='VectorGraph.FloatAttributeVector.values', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=548,
)

_VECTORGRAPH_DOUBLEATTRIBUTEVECTOR = _descriptor.Descriptor(
  name='DoubleAttributeVector',
  full_name='VectorGraph.DoubleAttributeVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='VectorGraph.DoubleAttributeVector.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='VectorGraph.DoubleAttributeVector.target', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='VectorGraph.DoubleAttributeVector.values', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=653,
)

_VECTORGRAPH_STRINGATTRIBUTEVECTOR = _descriptor.Descriptor(
  name='StringAttributeVector',
  full_name='VectorGraph.StringAttributeVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='VectorGraph.StringAttributeVector.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='VectorGraph.StringAttributeVector.target', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='VectorGraph.StringAttributeVector.values', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=754,
)

_VECTORGRAPH = _descriptor.Descriptor(
  name='VectorGraph',
  full_name='VectorGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='VectorGraph.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='VectorGraph.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='VectorGraph.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nvertices', full_name='VectorGraph.nvertices', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nedges', full_name='VectorGraph.nedges', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='edges', full_name='VectorGraph.edges', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int32_vectors', full_name='VectorGraph.int32_vectors', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double_vectors', full_name='VectorGraph.double_vectors', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_vectors', full_name='VectorGraph.string_vectors', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_VECTORGRAPH_EDGE, _VECTORGRAPH_INT32ATTRIBUTEVECTOR, _VECTORGRAPH_FLOATATTRIBUTEVECTOR, _VECTORGRAPH_DOUBLEATTRIBUTEVECTOR, _VECTORGRAPH_STRINGATTRIBUTEVECTOR, ],
  enum_types=[
    _VECTORGRAPH_GRAPHTYPE,
    _VECTORGRAPH_ATTRIBUTETARGET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=838,
)

_VECTORGRAPH_EDGE.containing_type = _VECTORGRAPH
_VECTORGRAPH_INT32ATTRIBUTEVECTOR.fields_by_name['target'].enum_type = _VECTORGRAPH_ATTRIBUTETARGET
_VECTORGRAPH_INT32ATTRIBUTEVECTOR.containing_type = _VECTORGRAPH
_VECTORGRAPH_FLOATATTRIBUTEVECTOR.containing_type = _VECTORGRAPH
_VECTORGRAPH_DOUBLEATTRIBUTEVECTOR.fields_by_name['target'].enum_type = _VECTORGRAPH_ATTRIBUTETARGET
_VECTORGRAPH_DOUBLEATTRIBUTEVECTOR.containing_type = _VECTORGRAPH
_VECTORGRAPH_STRINGATTRIBUTEVECTOR.fields_by_name['target'].enum_type = _VECTORGRAPH_ATTRIBUTETARGET
_VECTORGRAPH_STRINGATTRIBUTEVECTOR.containing_type = _VECTORGRAPH
_VECTORGRAPH.fields_by_name['type'].enum_type = _VECTORGRAPH_GRAPHTYPE
_VECTORGRAPH.fields_by_name['edges'].message_type = _VECTORGRAPH_EDGE
_VECTORGRAPH.fields_by_name['int32_vectors'].message_type = _VECTORGRAPH_INT32ATTRIBUTEVECTOR
_VECTORGRAPH.fields_by_name['double_vectors'].message_type = _VECTORGRAPH_DOUBLEATTRIBUTEVECTOR
_VECTORGRAPH.fields_by_name['string_vectors'].message_type = _VECTORGRAPH_STRINGATTRIBUTEVECTOR
_VECTORGRAPH_GRAPHTYPE.containing_type = _VECTORGRAPH
_VECTORGRAPH_ATTRIBUTETARGET.containing_type = _VECTORGRAPH
DESCRIPTOR.message_types_by_name['VectorGraph'] = _VECTORGRAPH

VectorGraph = _reflection.GeneratedProtocolMessageType('VectorGraph', (_message.Message,), dict(

  Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), dict(
    DESCRIPTOR = _VECTORGRAPH_EDGE,
    __module__ = 'graph_vector_pb2'
    # @@protoc_insertion_point(class_scope:VectorGraph.Edge)
    ))
  ,

  Int32AttributeVector = _reflection.GeneratedProtocolMessageType('Int32AttributeVector', (_message.Message,), dict(
    DESCRIPTOR = _VECTORGRAPH_INT32ATTRIBUTEVECTOR,
    __module__ = 'graph_vector_pb2'
    # @@protoc_insertion_point(class_scope:VectorGraph.Int32AttributeVector)
    ))
  ,

  FloatAttributeVector = _reflection.GeneratedProtocolMessageType('FloatAttributeVector', (_message.Message,), dict(
    DESCRIPTOR = _VECTORGRAPH_FLOATATTRIBUTEVECTOR,
    __module__ = 'graph_vector_pb2'
    # @@protoc_insertion_point(class_scope:VectorGraph.FloatAttributeVector)
    ))
  ,

  DoubleAttributeVector = _reflection.GeneratedProtocolMessageType('DoubleAttributeVector', (_message.Message,), dict(
    DESCRIPTOR = _VECTORGRAPH_DOUBLEATTRIBUTEVECTOR,
    __module__ = 'graph_vector_pb2'
    # @@protoc_insertion_point(class_scope:VectorGraph.DoubleAttributeVector)
    ))
  ,

  StringAttributeVector = _reflection.GeneratedProtocolMessageType('StringAttributeVector', (_message.Message,), dict(
    DESCRIPTOR = _VECTORGRAPH_STRINGATTRIBUTEVECTOR,
    __module__ = 'graph_vector_pb2'
    # @@protoc_insertion_point(class_scope:VectorGraph.StringAttributeVector)
    ))
  ,
  DESCRIPTOR = _VECTORGRAPH,
  __module__ = 'graph_vector_pb2'
  # @@protoc_insertion_point(class_scope:VectorGraph)
  ))
_sym_db.RegisterMessage(VectorGraph)
_sym_db.RegisterMessage(VectorGraph.Edge)
_sym_db.RegisterMessage(VectorGraph.Int32AttributeVector)
_sym_db.RegisterMessage(VectorGraph.FloatAttributeVector)
_sym_db.RegisterMessage(VectorGraph.DoubleAttributeVector)
_sym_db.RegisterMessage(VectorGraph.StringAttributeVector)


_VECTORGRAPH_INT32ATTRIBUTEVECTOR.fields_by_name['values'].has_options = True
_VECTORGRAPH_INT32ATTRIBUTEVECTOR.fields_by_name['values']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_VECTORGRAPH_FLOATATTRIBUTEVECTOR.fields_by_name['values'].has_options = True
_VECTORGRAPH_FLOATATTRIBUTEVECTOR.fields_by_name['values']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_VECTORGRAPH_DOUBLEATTRIBUTEVECTOR.fields_by_name['values'].has_options = True
_VECTORGRAPH_DOUBLEATTRIBUTEVECTOR.fields_by_name['values']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
