"""Public visualization settings key contracts.

This module is the stable public facade for downstream projects that need to
type-check Graphistry URL parameters and React-facing visualization settings.
"""

from typing import FrozenSet, Tuple, Union, cast, get_args

from typing_extensions import Literal, TypeAlias

from graphistry.models.surfaces.graphistry_frontend import (
    APPLY_ENCODINGS_REACT_KEY_SET as _APPLY_ENCODINGS_REACT_KEY_SET,
    APPLY_ENCODINGS_REACT_KEYS as _APPLY_ENCODINGS_REACT_KEYS,
    GRAPHISTRY_FRONTEND_CONTRACT_SIGNATURE,
    GRAPHISTRY_FRONTEND_CONTRACT_SIGNATURES_BY_VERSION,
    GRAPHISTRY_FRONTEND_CONTRACT_VERSION,
    GRAPHISTRY_FRONTEND_UPSTREAM_VERSIONS,
    REACT_SETTING_NAME_SET as _REACT_SETTING_NAME_SET,
    REACT_SETTING_NAMES as _REACT_SETTING_NAMES,
    URL_PARAM_NAME_SET as _URL_PARAM_NAME_SET,
    URL_PARAM_NAMES as _URL_PARAM_NAMES,
    ApplyEncodingsReactKey,
    ApplyEncodingsReactSettingsDict,
    FrontendContractVersionInfo,
    KnownReactSettingsDict,
    KnownURLParamsDict,
    ReactColorEncodingKey,
    ReactColorEncodingPayload,
    ReactEncodingMapping,
    ReactEncodingPalette,
    ReactEncodingVariation,
    ReactIconEncodingKey,
    ReactIconEncodingPayload,
    ReactNumericEncodingKey,
    ReactSettingsDict,
    ReactSizeEncodingKey,
    ReactSizeEncodingPayload,
    ReactTextEncodingKey,
    ReactTextEncodingPayload,
    SettingsValue,
    URLParamsDict,
    apply_encodings_keys,
    graphistry_frontend_contract_version_info,
    react_setting_keys,
    url_param_keys,
)

URLParamName: TypeAlias = Literal[
    "bg",
    "bottom",
    "collections",
    "collectionsGlobalEdgeColor",
    "collectionsGlobalNodeColor",
    "dissuadeHubs",
    "edgeCurvature",
    "edgeInfluence",
    "edgeOpacity",
    "favicon",
    "gravity",
    "info",
    "labelBackground",
    "labelColor",
    "labelOpacity",
    "left",
    "linLog",
    "lockedR",
    "lockedX",
    "lockedY",
    "logoAutoInvert",
    "logoMaxHeight",
    "logoMaxWidth",
    "logoPosition",
    "logoUrl",
    "menu",
    "neighborhoodHighlight",
    "neighborhoodHighlightHops",
    "pageTitle",
    "play",
    "pointOpacity",
    "pointSize",
    "pointStrokeWidth",
    "pointsOfInterestMax",
    "precisionVsSpeed",
    "right",
    "scalingRatio",
    "shortenLabels",
    "showActions",
    "showArrows",
    "showCollections",
    "showHistograms",
    "showInspector",
    "showLabelOnHover",
    "showLabelPropertiesOnHover",
    "showLabels",
    "showPointsOfInterest",
    "showPointsOfInterestLabel",
    "splashAfter",
    "strongGravity",
    "top",
]

ReactSettingName: TypeAlias = Literal[
    "axes",
    "backgroundColor",
    "controls",
    "edgeCurvature",
    "edgeInfluence",
    "edgeOpacity",
    "encodeAxis",
    "encodeEdgeColor",
    "encodeEdgeIcons",
    "encodePointColor",
    "encodePointIcons",
    "encodePointSize",
    "exclusions",
    "filters",
    "gravity",
    "dissuadeHubs",
    "iframeStyle",
    "labelBackground",
    "labelColor",
    "labelOpacity",
    "linLog",
    "lockedR",
    "lockedX",
    "lockedY",
    "neighborhoodHighlight",
    "neighborhoodHighlightHops",
    "play",
    "pointOpacity",
    "pointSize",
    "pointsOfInterestMax",
    "precisionVsSpeed",
    "pruneOrphans",
    "scalingRatio",
    "showArrows",
    "showHistograms",
    "showInfo",
    "showInspector",
    "showLabelActions",
    "showLabelInspector",
    "showLabelOnHover",
    "showLabelPropertiesOnHover",
    "showLabels",
    "showMenu",
    "showPointsOfInterest",
    "showPointsOfInterestLabel",
    "showSplashScreen",
    "showTimebars",
    "showToolbar",
    "strongGravity",
    "ticks",
    "type",
    "workbook",
]

VizSettingName: TypeAlias = Union[URLParamName, ReactSettingName]

URL_PARAM_NAMES: Tuple[URLParamName, ...] = cast(Tuple[URLParamName, ...], _URL_PARAM_NAMES)
URL_PARAM_NAME_SET: FrozenSet[URLParamName] = cast(FrozenSet[URLParamName], _URL_PARAM_NAME_SET)
REACT_SETTING_NAMES: Tuple[ReactSettingName, ...] = cast(Tuple[ReactSettingName, ...], _REACT_SETTING_NAMES)
REACT_SETTING_NAME_SET: FrozenSet[ReactSettingName] = cast(
    FrozenSet[ReactSettingName],
    _REACT_SETTING_NAME_SET,
)
APPLY_ENCODINGS_REACT_KEYS: Tuple[ApplyEncodingsReactKey, ...] = _APPLY_ENCODINGS_REACT_KEYS
APPLY_ENCODINGS_REACT_KEY_SET: FrozenSet[ApplyEncodingsReactKey] = _APPLY_ENCODINGS_REACT_KEY_SET
VIZ_SETTING_NAMES: Tuple[VizSettingName, ...] = cast(
    Tuple[VizSettingName, ...],
    tuple(dict.fromkeys((*URL_PARAM_NAMES, *REACT_SETTING_NAMES))),
)
VIZ_SETTING_NAME_SET: FrozenSet[VizSettingName] = frozenset(VIZ_SETTING_NAMES)

if tuple(get_args(URLParamName)) != URL_PARAM_NAMES:
    raise ValueError("URLParamName must match URL_PARAM_NAMES")
if tuple(get_args(ReactSettingName)) != REACT_SETTING_NAMES:
    raise ValueError("ReactSettingName must match REACT_SETTING_NAMES")

__all__ = [
    "APPLY_ENCODINGS_REACT_KEYS",
    "APPLY_ENCODINGS_REACT_KEY_SET",
    "ApplyEncodingsReactKey",
    "ApplyEncodingsReactSettingsDict",
    "FrontendContractVersionInfo",
    "GRAPHISTRY_FRONTEND_CONTRACT_SIGNATURE",
    "GRAPHISTRY_FRONTEND_CONTRACT_SIGNATURES_BY_VERSION",
    "GRAPHISTRY_FRONTEND_CONTRACT_VERSION",
    "GRAPHISTRY_FRONTEND_UPSTREAM_VERSIONS",
    "KnownReactSettingsDict",
    "KnownURLParamsDict",
    "REACT_SETTING_NAMES",
    "REACT_SETTING_NAME_SET",
    "ReactColorEncodingKey",
    "ReactColorEncodingPayload",
    "ReactEncodingMapping",
    "ReactEncodingPalette",
    "ReactEncodingVariation",
    "ReactIconEncodingKey",
    "ReactIconEncodingPayload",
    "ReactNumericEncodingKey",
    "ReactSettingName",
    "ReactSettingsDict",
    "ReactSizeEncodingKey",
    "ReactSizeEncodingPayload",
    "ReactTextEncodingKey",
    "ReactTextEncodingPayload",
    "SettingsValue",
    "URL_PARAM_NAMES",
    "URL_PARAM_NAME_SET",
    "URLParamName",
    "URLParamsDict",
    "VIZ_SETTING_NAMES",
    "VIZ_SETTING_NAME_SET",
    "VizSettingName",
    "apply_encodings_keys",
    "graphistry_frontend_contract_version_info",
    "react_setting_keys",
    "url_param_keys",
]
