---
- name: Find DNS server in use by remote host
  command: awk 'BEGIN {dns="8.8.8.8"} /^nameserver/ {dns=$2; exit;} END {print dns;}' /etc/resolv.conf
  register: remote_dns_server

- name: Set dns_server variable for use in nginx config file templates
  set_fact: dns_server="{{ remote_dns_server.stdout | default("8.8.8.8") }}"

- name: Install official nginx apt repo signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  become: yes

# 'Mainline' nginx branch is considered to be 'newest and mostly stable', and reccomended
- name: Add official nginx apt repo
  apt_repository: "repo='deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_lsb.codename }} nginx' state=present update_cache=yes"
  become: yes

- name: Add official nginx apt source repo
  apt_repository: "repo='deb-src http://nginx.org/packages/mainline/ubuntu/ {{ ansible_lsb.codename }} nginx' state=present update_cache=yes"
  become: yes

# There is a Ubuntu bug that causes upgrades from 1.4.6 (Ubuntu repo) to 1.9.11 (official nginx r
# epo) to fail. Uninstalling nginx-common (a dependency of 1.4.6 package) before upgrading fixes it.
- name: Remove old nginx-common
  apt: pkg=nginx-common
       state=absent
       update_cache=yes
       cache_valid_time=600
  become: yes
  notify: Restart nginx

- name: Install nginx
  apt: pkg=nginx=1.9.11-1~trusty
       update_cache=yes
       cache_valid_time=600
  become: yes
  notify: Restart nginx

- name: Configure nginx for proxy (main config file)
  copy: src=nginx.conf
        dest=/etc/nginx/nginx.conf
        owner=root
        group=graphistry-dev
        mode=0664
  become: yes
  notify: Restart nginx

- name: Configure nginx for proxy (individual config file)
  copy: src={{ item }}
        dest=/etc/nginx/conf.d/{{ item | basename }}
        owner=root
        group=graphistry-dev
        mode=0664
  notify: Restart nginx
  with_fileglob:
    - nginx.conf.d/*

# - name: print stuff
#   debug: msg="IP network {{ ansible_default_ipv4.network }}"

- name: Disable nginx for proxy default site
  file: path=/etc/nginx/sites-enabled/default
        state=absent
  sudo_user: root
  notify: Restart nginx
  tags:
    - nginx
  become: yes

- name: Configure nginx for proxy to proxy to nodejs
  template: src=proxy.site.j2
            dest=/etc/nginx/sites-enabled/10-proxy
            owner=root
            group=graphistry-dev
            mode=0664
  become: yes
  notify: Restart nginx

- name: Configure nginx for proxy to support SSL
  template: src=ssl.site.j2
            dest=/etc/nginx/sites-enabled/15-ssl
            owner=root
            group=graphistry-dev
            mode=0664
  become: yes
  notify: Restart nginx
