---
# We need have a `resolver` directive in nginx's config file because, listing the DNS server we want
# it to use. If we don't, it just uses the system's, but caches DNS lookups indefinitely. See, e.g.,
# https://trac.nginx.org/nginx/ticket/658 .
- name: Find DNS server in use by remote host
  command: awk 'BEGIN {dns="8.8.8.8"} /^nameserver/ {dns=$2; exit;} END {print dns;}' /etc/resolv.conf
  register: remote_dns_server

- name: Set dns_server variable for use in nginx config file templates
  set_fact: dns_server="{{ remote_dns_server.stdout | default("8.8.8.8") }}"

- name: Install official nginx apt repo signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  become: yes

# 'Mainline' nginx branch is considered to be 'newest and mostly stable', and reccomended
- name: Add official nginx apt repo
  apt_repository: "repo='deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_lsb.codename }} nginx' state=present update_cache=yes"
  become: yes

- name: Add official nginx apt source repo
  apt_repository: "repo='deb-src http://nginx.org/packages/mainline/ubuntu/ {{ ansible_lsb.codename }} nginx' state=present update_cache=yes"
  become: yes

# There is a Ubuntu bug that causes upgrades from 1.4.6 (Ubuntu repo) to 1.9.11 (official nginx r
# epo) to fail. Uninstalling nginx-common (a dependency of 1.4.6 package) before upgrading fixes it.
- name: Remove old nginx-common
  apt: pkg=nginx-common
       state=absent
       update_cache=yes
       cache_valid_time=600
  become: yes

- name: Install nginx
  apt: pkg=nginx
       update_cache=yes
       cache_valid_time=600
  become: yes
  notify: Restart nginx

- name: Upload Graphistry SSL files to remote host
  copy: src=ssl
        dest=/etc/nginx/graphistry
        owner=root
        group=root
        mode=0600
        directory_mode=0700
  become: yes
  notify: Restart nginx

- name: Create directory for Graphistry nginx config files
  file: path=/etc/nginx/graphistry
        state=directory
        owner=root
        group=graphistry-dev
        mode=0775
  become: yes

- name: Set nginx Graphistry app configuration
  template: src={{ item }}.j2
            dest=/etc/nginx/graphistry/{{ item }}
            owner=root
            group=graphistry-dev
            mode=0664
  become: yes
  notify: Restart nginx
  with_items:
    - server.conf
    - ssl.conf
    - upstreams-central.conf
    - upstreams-workers.conf
    - routes-workers.conf

- name: Set nginx main configuration
  copy: src=nginx.conf
        dest=/etc/nginx/nginx.conf
        owner=root
        group=graphistry-dev
        mode=0664
  become: yes
  notify: Restart nginx
