---
- name: Ensure viz-server install path is owned by user 'www'
  sudo: yes
  sudo_user: root
  file: path={{ graphistry_install_path }}
        state=directory
        recurse=no
        owner=www
        group=www
        mode=0775

- name: Ensure everything in install path can be read/written to by group 'www'
  sudo: yes
  sudo_user: root
  file: path={{ graphistry_install_path }}
        state=directory
        recurse=yes
        group=www
        mode='g+rw'

- name: Configure Supervisor to run viz-server workers
  template: src=viz_workers.conf.j2
            dest=/etc/supervisor/conf.d/viz_workers.conf
            owner=root
            group=graphistry-dev
            mode=0664
  register: worker_supervisor_conf
  notify: Add workers to Supervisor
  sudo: yes
  sudo_user: root

- name: Delete worker's old node_modules directory
  file: path={{ graphistry_install_path }}/viz-server/node_modules
        state=absent
  sudo: yes
  sudo_user: root

- name: Clone viz-server repo
  git: repo=git@github.com:graphistry/viz-server.git
       dest={{ graphistry_install_path }}/viz-server
       version="{{ viz_module_checkout }}"
       update=yes
       key_file=/home/{{ sudo_user }}/.ssh/deploy_id_rsa
       accept_hostkey=yes
  notify: Restart workers

- name: Install viz-server module
  npm: path={{ graphistry_install_path }}/viz-server
       state=latest
  environment: cuda_env
  notify: Restart workers