---
# Downloads and installs the Boundary Meter utility using their own install script.

# The script just adds their Apt repo and installs a package from it, but exports some vars first
# (based off your API key) that the pkg install script picks up. We can't easily recreate the
# script in Ansible, but once installed, apt-get will keep it updated.

# This should use the get_url or uri module, but the former can't send headers, and the latter has
# a bug where it strips quote escapes in the source file when it tries to save the file.
- name: Download Boundary Meter install script
  command: "curl -fsS -o '{{ ansible_files }}/setup_meter.sh' -d '{\"token\":\"{{ boundary_password }}\"}' -H 'Content-Type: application/json' https://meter.boundary.com/setup_meter
           creates='{{ ansible_files }}/setup_meter.sh'
           chdir='{{ ansible_files }}'"
  sudo: no

- name: Make Boundary Meter install script executable
  file: path="{{ ansible_files }}/setup_meter.sh"
        mode=0777
  sudo: no

- name: Run Boundary Meter install script
  command: creates="/etc/apt/sources.list.d/boundary.list"
           "{{ ansible_files }}/setup_meter.sh"
  sudo: no

- name: Fix Boundary Meter apt source file permissions
  file: path="/etc/apt/sources.list.d/boundary.list"
        mode=0644
        owner=root
        group=root
  sudo: yes
