---
# Installs the Splunk Universal Forwarder and configures it to be a deployment client of our Splunk
# server. Also installs Boundary Meter.

- name: Install sysstat for use by Splunk Add-on for Unix
  apt: pkg=sysstat
       state=latest
       update_cache=yes
       cache_valid_time=600

- name: Downlad Splunk Universal Forwarder
  sudo: no
  get_url: url="http://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=Linux&version=6.2.1&product=universalforwarder&filename=splunkforwarder-6.2.1-245427-linux-2.6-amd64.deb&wget=true"
           dest="{{ ansible_files }}/splunkforwarder-6.2.1-245427-linux-2.6-amd64.deb"
           sha256sum=4f37add3f0ef900a80891b234d892f05ca59868f9e507ae8de720261dd9876a2

- name: Install Splunk Universal Forwarder
  apt: deb="{{ ansible_files }}/splunkforwarder-6.2.1-245427-linux-2.6-amd64.deb"
       state=present

- name: Start Splunk Forwarder
  command: /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes
  register: start_splunk
  changed_when: "'already running' not in start_splunk.stdout"

- name: Enable Splunk Forwarder to start at boot
  command: /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes chdir=/opt/splunkforwarder/bin
  register: splunk_boot_start
  changed_when: "'Adding' in splunk_boot_start.stdout"

- name: Change default credentials on Splunk Forwarder (it's OK if this fails)
  command: /opt/splunkforwarder/bin/splunk edit user admin -password {{ splunk_forwarder_password }} -auth admin:changeme --answer-yes
  ignore_errors: true

- name: Configure Splunk Forwarder host name
  template: src=inputs.conf.j2
            dest=/opt/splunkforwarder/etc/system/local/inputs.conf
            owner=root
            group=root
            mode=0664
  notify: Restart Splunk

- name: Configure Splunk Forwarder server name
  ini_file: dest=/opt/splunkforwarder/etc/system/local/server.conf
            section=general
            option=serverName
            value="{{ inventory_hostname }}"
            owner=root
            group=root
            mode=0664
  notify: Restart Splunk

- name: Configure Splunk deployment server to Splunk Forwarder
  template: src=deploymentclient.conf.j2
            dest=/opt/splunkforwarder/etc/system/local/deploymentclient.conf
            owner=root
            group=root
            mode=0664
  notify: Restart Splunk

# - { include: boundary.yml, tags: [ 'boundary' ] }
