"""Shared case data for GFQL amplification tests."""

from graphistry.compute import n, e_forward, e_reverse, e_undirected, is_in
from graphistry.compute.gfql.same_path_types import col, compare


YANNAKAKIS_PRINCIPLE_CASES = [
    (
        [{"id": "a", "v": 5}, {"id": "b", "v": 6}, {"id": "c", "v": 10}, {"id": "x", "v": 4}, {"id": "y", "v": 1}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}, {"src": "a", "dst": "x"}, {"src": "x", "dst": "y"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"a", "b", "c"},
        {"x", "y"},
        {("a", "b"), ("b", "c")},
        {("a", "x")},
        None,
        None,
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 5}, {"id": "c", "v": 6}, {"id": "d", "v": 10}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "d"}, {"src": "a", "dst": "c"}, {"src": "c", "dst": "d"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        set(),
        set(),
        {("a", "b"), ("b", "d"), ("a", "c"), ("c", "d")},
        set(),
        {"a", "b", "c", "d"},
        None,
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 5}, {"id": "c", "v": 10}, {"id": "x", "v": 20}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}, {"src": "b", "dst": "x"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"x"},
        set(),
        {("a", "b"), ("b", "c")},
        set(),
        None,
        None,
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 100}, {"id": "c", "v": 5}, {"id": "d", "v": 10}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}, {"src": "c", "dst": "d"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=3, max_hops=3), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        set(),
        set(),
        set(),
        set(),
        {"a", "b", "c", "d"},
        None,
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 5}, {"id": "c", "v": 6}, {"id": "d", "v": 10}],
        [{"src": "a", "dst": "b"}, {"src": "a", "dst": "c"}, {"src": "b", "dst": "d"}, {"src": "c", "dst": "d"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        set(),
        set(),
        set(),
        set(),
        {"a", "b", "c", "d"},
        4,
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 5}, {"id": "c", "v": 10}, {"id": "x", "v": 3}, {"id": "y", "v": 0}, {"id": "p", "v": 4}, {"id": "q", "v": 2}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}, {"src": "a", "dst": "x"}, {"src": "x", "dst": "y"}, {"src": "a", "dst": "p"}, {"src": "p", "dst": "q"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"a", "b", "c", "p", "q"},
        {"x", "y"},
        set(),
        set(),
        None,
        None,
    ),
]

YANNAKAKIS_PRINCIPLE_IDS = [
    "dead_end_branch_pruning",
    "all_valid_paths_included",
    "spurious_edge_exclusion",
    "where_prunes_intermediate_edges",
    "convergent_diamond_all_paths_included",
    "mixed_valid_invalid_branches",
]

HOP_LABEL_PATTERNS_CASES = [
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 5}, {"id": "c", "v": 6}, {"id": "d", "v": 10}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "d"}, {"src": "a", "dst": "c"}, {"src": "c", "dst": "d"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"a", "b", "c", "d"},
        set(),
        set(),
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 2}, {"id": "c", "v": 5}, {"id": "d", "v": 10}],
        [{"src": "a", "dst": "c"}, {"src": "b", "dst": "c"}, {"src": "c", "dst": "d"}],
        [n({"v": is_in([1, 2])}, name="start"), e_forward(min_hops=1, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        None,
        {"a", "b", "c", "d"},
        set(),
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 3}, {"id": "c", "v": 5}, {"id": "d", "v": 10}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}, {"src": "c", "dst": "d"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=3), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"a", "b", "c", "d"},
        set(),
        set(),
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 5}, {"id": "c", "v": 10}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}],
        [n({"id": "a"}, name="start"), e_undirected(min_hops=1, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        None,
        {"a", "b", "c"},
        set(),
    ),
]

HOP_LABEL_PATTERNS_IDS = [
    "hop_labels_dont_affect_validity",
    "multiple_seeds_hop_labels",
    "hop_labels_with_min_hops",
    "undirected_hop_labels",
]

SENSITIVE_PHENOMENA_CASES = [
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 5}, {"id": "c", "v": 10}, {"id": "d", "v": 2}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}, {"src": "d", "dst": "b"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=1, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"b", "c"},
        {"d"},
        set(),
    ),
    (
        [{"id": "a", "v": 10}, {"id": "b", "v": 5}, {"id": "c", "v": 1}],
        [{"src": "b", "dst": "a"}, {"src": "c", "dst": "b"}],
        [n({"id": "a"}, name="start"), e_reverse(min_hops=1, max_hops=2), n(name="end")],
        [compare(col("start", "v"), ">", col("end", "v"))],
        {"b", "c"},
        set(),
        set(),
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 10}],
        [{"src": "b", "dst": "a"}],
        [n({"id": "a"}, name="start"), e_undirected(min_hops=1, max_hops=1), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"b"},
        set(),
        set(),
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 100}, {"id": "c", "v": 50}, {"id": "d", "v": 10}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}, {"src": "c", "dst": "d"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=2), n(name="middle"), e_forward(min_hops=1, max_hops=1), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"d"},
        set(),
        set(),
    ),
    (
        [{"id": "a", "v": 1, "type": "X"}, {"id": "b", "v": 5, "type": "Y"}, {"id": "c", "v": 10, "type": "X"}, {"id": "d", "v": 20, "type": "Z"}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}, {"src": "b", "dst": "d"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v")), compare(col("start", "type"), "==", col("end", "type"))],
        {"c"},
        {"d"},
        set(),
    ),
    (
        [{"id": "a", "v": 5}, {"id": "b", "v": 10}],
        [{"src": "a", "dst": "b"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=0, max_hops=1), n(name="end")],
        [compare(col("start", "v"), "<=", col("end", "v"))],
        {"a", "b"},
        set(),
        set(),
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 5}, {"id": "c", "v": 10}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=1, max_hops=10), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"b", "c"},
        set(),
        set(),
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 5}, {"id": "c", "v": 10}, {"id": "d", "v": 15}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}, {"src": "b", "dst": "d"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"c", "d"},
        set(),
        {("a", "b")},
    ),
    (
        [{"id": "a", "v": 5}, {"id": "b", "v": 10}],
        [{"src": "a", "dst": "a"}, {"src": "a", "dst": "b"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=1, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<=", col("end", "v"))],
        {"b"},
        set(),
        set(),
    ),
    (
        [{"id": "a", "v": 5}, {"id": "b", "v": 3}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "a"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=2, max_hops=2), n(name="end")],
        [compare(col("start", "v"), "<=", col("end", "v"))],
        {"a"},
        set(),
        set(),
    ),
    (
        [{"id": "a", "v": 1}, {"id": "b", "v": 2}, {"id": "c", "v": 3}, {"id": "d", "v": 10}],
        [{"src": "a", "dst": "b"}, {"src": "b", "dst": "c"}, {"src": "c", "dst": "a"}, {"src": "c", "dst": "d"}],
        [n({"id": "a"}, name="start"), e_forward(min_hops=1, max_hops=3), n(name="end")],
        [compare(col("start", "v"), "<", col("end", "v"))],
        {"b", "c", "d"},
        set(),
        set(),
    ),
]

SENSITIVE_PHENOMENA_IDS = [
    "asymmetric_graph_forward_only_node",
    "asymmetric_graph_reverse_only_node",
    "undirected_finds_reverse_only_node",
    "three_step_start_to_end_comparison",
    "multiple_non_adjacent_constraints",
    "min_hops_zero_includes_seed",
    "max_hops_exceeds_graph_diameter",
    "edge_used_by_multiple_destinations",
    "self_loop_edge",
    "small_cycle_with_min_hops",
    "cycle_with_branch",
]
