---

# TODO: Secure sensitive data:
# * Username/password variable files should be encrypted and/or distributed out-of-band.
# * No Ansible SSH private key in repo (users use their own SSH keys to log in either as `ubuntu`,
#   like present, or even as their own user account.)
# * Review account creation and permissions on 'production' machines.
# * Consider requiring passwords for `sudo` (refactor Ansible to prompt users for sudo password.)

- hosts: localhost
  gather_facts: no
  roles:
    - { role: slack, message: "NVIDIA-Docker host configuration started..." }

- hosts: dockerhost
  gather_facts: no
  roles:
    - sshd_port

- hosts: dockerhost
  roles:
    - { role: docker }
    - { role: cuda }
    - { role: nvidiadocker }

- hosts: localhost
  gather_facts: no
  roles:
    - { role: slack, message: "NVIDIA-Docker host configured." }
