---

# FIXME: Only refresh the apt-cache when installing nodejs if we installed new repos
# FIXME: Only restart splunk service if we've changed its config


- hosts: localhost
  roles:
    - { role: slack, message: "{{ deployment }} deploy started..." }
  tags:
    - provision
    - deploy
    - local

- hosts: workers:central
  roles:
   - { role: common, sudo: yes }
   - { role: users }
   - { role: splunkfwd, sudo: yes }
   - { role: nodejs }
  tags:
    - common
    - provision

- hosts: workers
  roles:
   - { role: worker, tags: prod-full }
   - { role: viz-app, sudo: yes, sudo_user: www, tags: [ 'deploy', 'new_deploy' ] }
  tags: workers

- hosts: central
  roles:
   - { role: central, tags: prod-full }
  tags: central

- hosts: localhost
  roles:
    - { role: slack, message: "...{{ deployment }} deploy done! Access at {{ www_url }}." }
  tags:
    - provision
    - deploy
    - local