Vagrant.configure("2") do |config|

  config.vm.network :forwarded_port, host: 3000, guest: 80
  config.vm.network :forwarded_port, host: 10000, guest: 10000
  config.vm.network :forwarded_port, host: 10001, guest: 10001
  config.vm.network :forwarded_port, host: 10002, guest: 10002

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "dev" do |box|
    box.vm.box = "ubuntu/trusty64"
  end

end
