---

- name: Stop the old mongo
  sudo: yes
  sudo_user: root
  command: "docker rm -f graphistry_mongo"
  ignore_errors: yes

- name: Start mongo
  sudo: yes
  sudo_user: root
  command: "docker run --restart=unless-stopped --name graphistry_mongo --net host -d mongo:2"

- name: Allow a slow start
  command: sleep 1

- name: Add graphistry user
  sudo: yes
  sudo_user: root
  command: "docker exec graphistry_mongo mongo --eval 'db.getUser(\"{{ mongo_username }}\") || db.createUser({user: \"{{ mongo_username }}\", pwd: \"{{ mongo_password }}\", roles: [\"readWrite\"]})' localhost/{{ mongo_name }}"

- name: Test that mongo works
  sudo: yes
  sudo_user: root
  command: "docker exec graphistry_mongo mongo --eval '2+2' -u {{ mongo_username }} -p {{ mongo_password }} localhost/{{ mongo_name }}"

- name: Add expiry of gpu_monitor
  sudo: yes
  sudo_user: root
  command: "docker exec graphistry_mongo mongo --eval 'db.gpu_monitor.createIndex({updated: 1}, {expireAfterSeconds: 30})' -u {{ mongo_username }} -p {{ mongo_password }} {{ mongo_host }}/{{ mongo_name }}"

- name: Add expiry of node_monitor
  sudo: yes
  sudo_user: root
  command: "docker exec graphistry_mongo mongo --eval 'db.node_monitor.createIndex({updated: 1}, {expireAfterSeconds: 90})' -u {{ mongo_username }} -p {{ mongo_password }} {{ mongo_host }}/{{ mongo_name }}"
