---
- name: Check Ansible version
  fail: msg="Your version of ansible is too old. You need at least version {{ ansible_minimum_version }} to run this playbook, but you are running version {{ ansible_version.full }}."
  when: not (ansible_version | version_compare(ansible_minimum_version, '>='))
  run_once: true
  tags:
    - version_check
    - deploy
    - provision
    - worker
    - central