---
- hosts: all
  tasks:
    - name: Make directory
      command: mkdir /var/graphistry/{{ deploy_directory }}

    - name: Copy release to deploy directory
      copy: src=release.tar.gz
            dest=/var/graphistry/{{ deploy_directory }}

    - name: Unpack release
      args:
        chdir: /var/graphistry/{{ deploy_directory }}
      command: tar -xvzf release.tar.gz

    - name: Load containers
      args:
        chdir: /var/graphistry/{{ deploy_directory }}
      command: ./load.sh

    - name: Launch containers with arbitrary bash parameters
      args:
        chdir: /var/graphistry/{{ deploy_directory }}
      command: bash -l -c "{{ arbitrary_parameters }} ./launch.sh"

    - name: GC old directories (keep last 2)
      args:
        chdir: /var/graphistry/{{ deploy_directory }}
      command: bash -c "rm -r `ls -t | tail -n +4`"

    - name: GC old containers
      command: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc
