from typing import Any

class TableVectorizer:
    def fit(self, *args: Any, **kwargs: Any) -> 'TableVectorizer': ...
    def transform(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit_transform(self, *args: Any, **kwargs: Any) -> Any: ...

