from typing import Any

class UMAP:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def fit(self, *args: Any, **kwargs: Any) -> 'UMAP': ...
    def transform(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit_transform(self, *args: Any, **kwargs: Any) -> Any: ...

