---
- command: hostname {{ hostname }}
  sudo: yes
  tags: common

- template: src=hostname.j2 dest=/etc/hostname
  sudo: yes
  tags: common

- template: src=hosts.j2 dest=/etc/hosts
  sudo: yes
  tags: common

- template: src=timezone.j2 dest=/etc/timezone owner=root group=root mode=0644
  sudo: yes
  tags: common

- command: rm /var/lib/apt/lists/lock
  sudo: yes
  ignore_errors: true
  tags: common

- command: rm /var/cache/apt/archives/lock
  sudo: yes
  ignore_errors: true
  tags: common

- command: dpkg --configure -a
  sudo: yes
  ignore_errors: true
  tags: common

- name: update apt
  apt: update_cache=yes
  sudo: yes
  tags: common

- name: install common tools
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - build-essential
    - htop
    - tcpflow
    - curl
    - git
    - vim
    - ack-grep
    - python-pip
    - npm
    - unattended-upgrades
    - python-psutil
    - supervisor
    - ntp
  tags: common

- name: create apt auto-upgrades job configuration
  template: >
    src=auto-upgrades.j2 dest=/etc/apt/apt.conf.d/20auto-upgrades
    owner=root group=root mode=0644
  sudo: yes
  tags: common

- name: create unattended-upgrades configuration
  template: >
    src=unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root group=root mode=0644
  sudo: yes
  tags: common

- name: install pip stuff
  pip: name={{ item }}
  sudo: yes
  with_items:
    - setuptools
    - distribute
    - pymongo
  tags: common

- name: sshd config
  template: src=sshd_config dest=/etc/ssh/sshd_config
  sudo: yes
  tags:
    - ssh
    - common

- command: service ssh restart
  sudo: yes
  tags:
    - ssh
    - common