---
- name: Set permissions on Ansible SSH key
  local_action:
    module: file
    path: "{{ playbook_dir }}/ansible_id_rsa.pem"
    owner: "{{ lookup('env','USER') }}"
    mode: 0600
  sudo: no
  tags:
    - local

- { include: sshd_port.yml, tags: [ 'sshd' ] }

- name: Gather facts for Common
  setup:
  sudo: no

- name: Create Ansible file folder
  sudo: no
  file: path="{{ ansible_env.HOME }}/ansible"
        state=directory

- name: Set fully-qualified domain name
  template: src=hosts.j2 dest=/etc/hosts

- name: Set hostname
  hostname: name="{{ hostname }}"

- name: Configure Ubuntu cloud-init to use our hostname and not overwrite it
  template: src=50graphistry-hostname.cfg.j2
            dest=/etc/cloud/cloud.cfg.d/50graphistry-hostname.cfg
            owner=root
            group=root
            mode=0644

- name: Configure timezone
  copy: src=timezone dest=/etc/timezone owner=root group=root mode=0644

- name: Upgrade packages
  apt: upgrade=dist
       state=latest
       update_cache=yes
       cache_valid_time=300
  tags:
    - system-upgrade
    - slow

- name: Install common tools
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=300
  with_items:
    - build-essential
    - htop
    - tcpflow
    - curl
    - git
    - vim
    - ack-grep
    - python-pip
    - unattended-upgrades
    - python-psutil
    - supervisor
    - ntp
    - pkg-config
    - acl
  tags: common

- name: Create apt auto-upgrades job configuration
  copy: src=auto-upgrades
        dest=/etc/apt/apt.conf.d/10periodic
        owner=root
        group=root
        mode=0644
        force=yes

- name: Enable ACLs on root filesystem
  mount: name=/
         src='LABEL=cloudimg-rootfs'
         fstype=ext4
         opts='defaults,acl,discard'
         state=mounted
  sudo: yes
