---
- { include: sshd_port.yml, tags: [ 'sshd' ] }

- name: Gather facts for Common
  setup:
  sudo: no

- name: Create Ansible file folder
  sudo: no
  file: path="{{ ansible_env.HOME }}/ansible"
        state=directory

- name: Set fully-qualified domain name
  template: src=hosts.j2 dest=/etc/hosts

- name: Set hostname
  hostname: name="{{ inventory_hostname_short }}"

- name: Configure Ubuntu cloud-init to use our hostname and not overwrite it
  template: src=50graphistry-hostname.cfg.j2
            dest=/etc/cloud/cloud.cfg.d/50graphistry-hostname.cfg
            owner=root
            group=root
            mode=0644

- name: Configure timezone
  copy: src=timezone dest=/etc/timezone owner=root group=root mode=0644

- name: Upgrade packages
  apt: upgrade=dist
       state=latest
       update_cache=yes
       cache_valid_time=300
  tags:
    - system-upgrade
    - slow

- name: Install common tools
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=600
  with_items:
    - build-essential
    - htop
    - tcpflow
    - curl
    - git
    - vim
    - ack-grep
    - python-pip
    - unattended-upgrades
    - python-psutil
    - supervisor
    - ntp
    - pkg-config
    - acl

- name: Create apt auto-upgrades job configuration
  copy: src=auto-upgrades
        dest=/etc/apt/apt.conf.d/10periodic
        owner=root
        group=root
        mode=0644
        force=yes

- name: Enable ACLs on root filesystem
  mount: name=/
         src='LABEL=cloudimg-rootfs'
         fstype=ext4
         opts='defaults,acl,discard'
         state=mounted
  sudo: yes

- name: Install Supervisor
  apt: pkg=supervisor
       state=latest
       update_cache=yes
       cache_valid_time=300
  register: supervisor_install
  sudo: yes
  sudo_user: root

- name: Configure Supervisor
  copy: src=supervisord.conf
        dest=/etc/supervisor/supervisord.conf
        owner=root
        group=root
        mode=0664
  sudo: yes
  sudo_user: root
  register: supervisor_configure

- name: Restart Supervisor
  service: name=supervisor
           state=restarted
           enabled=yes
  when: supervisor_install.changed or supervisor_configure.changed
  sudo: yes
  sudo_user: root