---
- name: Ensure Ansible version is 1.9 for compatability with our plabooks
  fail: msg="Ansible {{ ansible_version.full }} is currently incompatible with our playbooks. Please install Ansible 1.9.x instead."
  when: not ("%d.%d" | format(ansible_version.major, ansible_version.minor) | version_compare("1.9", "=="))
  run_once: true
  become: no
  tags:
    - version_check
    - preflight
    - deploy
    - provision
    - workers
    - central
    - deploy_server

- name: Create Ansible file folder
  become: no
  file: path="{{ ansible_files }}"
        state=directory
        owner=root
        mode=1777
        recurse=no
  become: yes
  become_user: root

- name: Configure timezone
  copy: content="US/Pacific-New"
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
  notify: Update timezone
  become: yes
  become_user: root

# - name: Upgrade packages
#   apt: upgrade=dist
#        state=latest
#        update_cache=yes
#        cache_valid_time=300
#   tags:
#     - system-upgrade
#     - slow

- name: Add git apt PPA repo (to get the most up-to-date git)
  apt_repository: repo='ppa:git-core/ppa'
  become: yes
  register: git_ppa

- name: Update apt cache for git PPA
  apt: update_cache=yes
  become: yes
  when: git_ppa.changed

- name: Install common tools
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=600
  with_items:
    - build-essential
    - curl
    - git
    - logrotate
    - vim
    - ack-grep
    - python-pip
    - unattended-upgrades
    - python-psutil
    - ntp
    - pkg-config
    - acl
    - schedtool
  become: yes

- name: Install common Python packages
  pip: name={{ item }}
  with_items:
    - setuptools
    - distribute
  become: yes

- name: Create apt auto-upgrades job configuration
  copy: src=auto-upgrades
        dest=/etc/apt/apt.conf.d/10periodic
        owner=root
        group=root
        mode=0644
        force=yes
  become: yes

- name: Enable ACLs on root filesystem
  mount: name=/
         src='LABEL=cloudimg-rootfs'
         fstype=ext4
         opts='defaults,acl,discard,barrier=0,noatime,nodiratime'
         state=mounted
  become: yes

# - name: Clone 'ec2-net-utils for Ubuntu' repo
#   git: repo=https://github.com/graphistry/ubuntu-ec2net.git
#        dest="{{ ansible_files }}/ubuntu-ec2net"
#        update=yes
#        accept_hostkey=yes
#   register: ec2_net_utils_repo
#
# - name: Install ec2-net-utils
#   command: make install
#            chdir="{{ ansible_files }}/ubuntu-ec2net"
#   when: ec2_net_utils_repo.changed
#   become: yes
#   become_user: root

- { include: tmp_mount.yml, tags: [ 'tmp_mount' ] }

# - { include: performance.yml, tags: [ 'performance' ] }
