---
- name: Set permissions on Ansible SSH key
  local_action:
    module: file
    path: "{{ playbook_dir }}/ansible_id_rsa.pem"
    owner: "{{ lookup('env','USER') }}"
    mode: 0600
  sudo: no
  tags:
    - provision
    - local

- { include: sshd_port.yml, tags: [ 'sshd' ] }

- name: Gather facts
  setup: filter='*'
  sudo: no

- name: Create Ansible file folder
  sudo: no
  file: path="{{ ansible_env.HOME }}/ansible"
        state=directory

- name: Set hostname
  command: hostname {{ hostname }}

- name: Configure hosts file to point system hostname to 127.0.0.1
  template: src=hosts.j2 dest=/etc/hosts
  sudo: yes
  tags: common

- name: Configure Ubuntu cloud-init to use our hostname and not overwrite it
  template: src=50graphistry-hostname.cfg.j2
            dest=/etc/cloud/cloud.cfg.d/50graphistry-hostname.cfg
            owner=root
            group=root
            mode=0644

- name: Set hosts file so hostname points to localhost
  tags: new-common
  lineinfile: dest=/etc/hosts
              regexp='^\s*127\.0\.0\.1\s+'
              line="127.0.0.1 localhost {{ hostname }}"
              state=present
              create=yes

- name: Configure timezone
  tags: new-common
  copy: src=timezone dest=/etc/timezone owner=root group=root mode=0644

# - command: rm /var/lib/apt/lists/lock
#   sudo: yes
#   ignore_errors: true
#   tags: common

# - command: rm /var/cache/apt/archives/lock
#   sudo: yes
#   ignore_errors: true
#   tags: common

# - command: dpkg --configure -a
#   sudo: yes
#   ignore_errors: true
#   tags: common

- name: Upgrade packages
  apt: upgrade=dist
       state=latest
       update_cache=yes
       cache_valid_time=300
  tags:
    - system-upgrade
    - slow

- name: Install common tools
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=300
  with_items:
    - build-essential
    - htop
    - tcpflow
    - curl
    - git
    - vim
    - ack-grep
    - python-pip
    - unattended-upgrades
    - python-psutil
    - supervisor
    - ntp
    - pkg-config
  tags: common

- name: Create apt auto-upgrades job configuration
  tags: common
  copy: src=auto-upgrades
        dest=/etc/apt/apt.conf.d/10periodic
        owner=root
        group=root
        mode=0644
        force=yes