---
# System configuration for performance (taken from http://www.brendangregg.com/blog/2015-03-03/performance-tuning-linux-instances-on-ec2.html)

- name: Tune filesystem rq_affinity
  shell: echo 2 > /sys/block/{{ item.key }}/queue/rq_affinity
  become: yes
  with_dict: ansible_devices

- name: Tune filesystem nr_requests
  shell: echo 256 > /sys/block/{{ item.key }}/queue/nr_requests
  become: yes
  with_dict: ansible_devices

# Some workloads, e.g., Cassandra, can be sensitive to read ahead size
- name: Tune filesystem read_ahead_kb
  shell: echo 256 > /sys/block/{{ item.key }}/queue/read_ahead_kb
  become: yes
  with_dict: ansible_devices

- name: Configure sysctl settings for performance
  copy: src=sysctl.d/
        dest=/etc/sysctl.d/
        owner=root
        group=root
        mode=0644
        directory_mode=0755
  become: yes
  notify: Apply sysctl settings

# Do we need to reboot to make these take effect?
# Alternatively, are these persistent between reboots?
