NODE_ID    = 'nodeID'
NODE_TITLE = 'pointTitle'

EDGE_ID     = 'edgeId'
EDGE_SRC    = 'source'
EDGE_DST    = 'destination'
EDGE_COLOR  = 'edgeColor'
EDGE_LABEL  = 'edgeLabel'
EDGE_TITLE  = 'edgeTitle'
EDGE_WEIGHT = 'edgeWeight'
NODE_COLOR  = 'pointColor'
NODE_LABEL  = 'pointLabel'
NODE_TITLE  = 'pointTitle'
NODE_SIZE   = 'pointSize'
