NODE_ID     = 'nodeId'
NODE_TITLE  = 'pointTitle'
NODE_COLOR  = 'pointColor'
NODE_LABEL  = 'pointLabel'
NODE_TITLE  = 'pointTitle'
NODE_SIZE   = 'pointSize'

EDGE_ID     = 'edgeId'
EDGE_SRC    = 'source'
EDGE_DST    = 'destination'
EDGE_COLOR  = 'edgeColor'
EDGE_LABEL  = 'edgeLabel'
EDGE_TITLE  = 'edgeTitle'
EDGE_WEIGHT = 'edgeWeight'
