---
- { include: CUDA.yml, tags: [ 'cuda' ] }

  with_items:
  sudo: yes
  tags: provision

  sudo: yes
  tags: worker

  sudo: yes
  tags: worker

- command: mkdir /tmp/web
  ignore_errors: true
  tags:
  - worker

- command: chown -R {{ ansible_ssh_user }}:{{ ansible_ssh_user }} /tmp/web
  sudo: yes
  tags:
  - worker

- shell: "npm config set prefix '/home/{{ ansible_ssh_user }}/.npm_global'"
  tags:
    - worker

- git: repo=git@github.com:graphistry/viz-server.git dest=/tmp/web/viz-server version=master update=yes accept_hostkey=yes
  tags:
    - worker
    - fast

- command: npm install --global grunt-cli
  tags:
    - worker

- command: npm install --global node-gyp
  tags:
    - worker

# TODO: Fix this. Not sure what's up with Ansible's users.
- shell: sudo su www -l -c "cd /home/www && npm install node-webcl"
  sudo: yes
  tags:
    - worker

- shell: sudo su www -l -c "cd /home/www && npm install node-webgl"
  sudo: yes
  tags:
    - worker

- shell: chdir=/home/{{ ansible_ssh_user }}/ npm install node-webcl
  tags:
    - worker

- shell: chdir=/home/{{ ansible_ssh_user }}/ npm install node-webgl
  tags:
    - worker

- shell: chdir=/tmp/web/viz-server npm install
  tags:
    - worker
    - fast

- name: Find temporary npm directories to delete
  command: find /tmp -maxdepth 1 -iname 'npm*'
  register: npm_to_delete
  tags:
    - worker
    - fast

- name: Deleting temporary npm directories
  file: path={{ item }} state=absent
  with_items: npm_to_delete.stdout_lines
  sudo: yes
  tags:
    - worker
    - fast

- command: cp -ru /tmp/web/viz-server /opt
  sudo: yes
  tags:
    - worker
    - fast

- command: chown -R www:www /opt/
  sudo: yes
  tags:
    - worker
    - fast

- command: chmod g+w -R /opt/
  sudo: yes
  tags:
    - worker
    - fast

- command: mkdir /var/log/worker
  ignore_errors: true
  sudo: yes
  tags: worker

# - include: supervisor.yml tags=deploy,supervisor,app
