---
- { include: CUDA.yml, tags: [ 'cuda' ] }

- name: Install pigz
  apt: pkg=pigz state=present update_cache=yes cache_valid_time=600
  sudo: yes

- name: Install Kerberos dev libs (needed for MongoDB node module)
  apt: pkg=libkrb5-dev state=installed update_cache=yes cache_valid_time=600
  sudo: yes
  sudo_user: root

- name: Install Python packages
  pip: name={{ item }}
  with_items:
    - setuptools
    - distribute
    - pymongo
  sudo: yes

- name: Create worker log folder
  sudo: yes
  file: path=/var/log/worker
        state=directory
        owner=www
        group=root
        mode=0777

- name: Set Supervisor config for reaper.py
  template: src=reaper.conf.j2
            dest=/etc/supervisor/conf.d/reaper.conf
            owner=root
            group=graphistry-dev
            mode=0664
  sudo: yes
  sudo_user: root
  notify: Add reaper.py to Supervisor
  tags:
    - supervisor
    - reaper

- name: Upload reaper.py
  template: src=reaper.py.j2
            dest={{ graphistry_install_path }}/reaper.py
            owner=www
            group=graphistry-dev
            mode=0775
  sudo: yes
  sudo_user: root
  notify: Restart reaper.py
  tags:
    - supervisor
    - reaper