---
- name: Gather facts for worker
  setup:
  sudo: no

- { include: CUDA.yml, tags: [ 'cuda' ] }

- name: Install Python packages
  pip: name={{ item }}
  with_items:
    - setuptools
    - distribute
    - pymongo
  sudo: yes

- name: Create worker log folder
  sudo: yes
  file: path=/var/log/worker
        state=directory
        owner=www
        group=root
        mode=0777

- name: Install Kerberos dev libs (needed for MongoDB node module)
  apt: pkg=libkrb5-dev state=installed update_cache=yes cache_valid_time=600
  sudo: yes
  sudo_user: root

- name: Install pigz
  apt: pkg=pigz state=installed update_cache=yes cache_valid_time=600
  sudo: yes


- include: supervisor.yml tags=deploy,supervisor
