---
- { include: CUDA.yml, tags: [ 'cuda' ] }

  with_items:
  sudo: yes
  tags: provision

  sudo: yes
  tags: worker

  sudo: yes
  tags: worker


# - include: supervisor.yml tags=deploy,supervisor,app
