---
# Ensure supervisord itself is running
- name: Starting Supervisor
  service: name=supervisor
           state=started
           enabled=yes
  sudo: yes

- name: add monitoring agent
  template: src=reaper.py.j2 dest={{ graphistry_install_path }}/reaper.py
  notify:
    - supervisor reload
  sudo: yes

- name: monitoring supervisor
  template: src=reaper.supervisor.j2 dest=/etc/supervisor/conf.d/reaper.conf
  notify:
    - update supervisor
  sudo: yes
