---
dependencies:
  # We have 'common' first because 'preflight' should not collect facts before common runs, due to
  # the fact that the server may have sshd running on the wrong port. common will detect and fix
  # this, but if preflight tries to collect facts first, it will fail to connect and the playbook
  # will fail.
- role: common
  sudo: yes
  tags:
    - common

- role: preflight
  tags: tags | to_nice_yaml

- role: splunkfwd
  sudo: yes
  tags:
    - splunk
