---
- name: Find npm cache items to delete (it's OK if this fails)
  command: ls -1 "{{ npm_temp_path }}/"
  ignore_errors: true
  sudo: yes
  sudo_user: root
  changed_when: False
  register: npm_cache_ls
  tags:
    - nodejs
    - npm
    - npm_cache_clear

- name: Delete npm cache items
  file: path="{{ npm_temp_path }}/{{ item }}"
        state=absent
  with_items: npm_cache_ls.stdout_lines
  sudo: yes
  sudo_user: root
  tags:
    - nodejs
    - npm
    - npm_cache_clear

- name: Create npm cache directory with proper permission
  file: path="{{ npm_temp_path }}"
        state=directory
        owner=root
        group=root
        mode=1777
  sudo: yes
  sudo_user: root
  tags:
    - nodejs
    - npm
    - npm_cache_clear

- name: Find home directories
  command: ls -1 /home
  register: ls_home
  changed_when: False
  tags:
    - nodejs
    - npm
    - npm_cache_clear

- name: Delete user npm cache
  file: path=/home/{{ item }}/.npm
        state=absent
  with_items: ls_home.stdout_lines
  sudo: yes
  sudo_user: root
  tags:
    - nodejs
    - npm
    - npm_cache_clear

- name: Delete user node-gyp cache
  file: path=/home/{{ item }}/.node-gyp
        state=absent
  with_items: ls_home.stdout_lines
  sudo: yes
  sudo_user: root
  tags:
    - nodejs
    - npm
    - npm_cache_clear
