---
- name: Create npm temp directory
  file: path="{{ npm_temp_path }}"
        state=directory
        recurse=no
        owner={{ node_user_name }}
        group=graphistry-dev
        mode=1777
  sudo: yes
  sudo_user: root

- name: Install Node Source APT repo key
  sudo: yes
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add Node Source APT repo
  sudo: yes
  apt_repository: "repo='deb https://deb.nodesource.com/node {{ ansible_lsb.codename }} main' state=present"
  register: added_node_repo

- name: Add Node Source APT source repo
  sudo: yes
  apt_repository: "repo='deb-src https://deb.nodesource.com/node {{ ansible_lsb.codename }} main' state=present"

- name: Update apt cache
  apt: update_cache=yes
  sudo: yes
  when: added_node_repo.changed

- name: Install Kerberos dev libs (needed for MongoDB node module)
  apt: pkg=libkrb5-dev state=installed update_cache=yes cache_valid_time=600
  sudo: yes
  sudo_user: root

- name: Install Node.js
  apt: name=nodejs state=latest update_cache=yes cache_valid_time=600
  sudo: yes

- { include: clear_caches.yml }

- name: Create graphistry app install directory
  sudo: yes
  sudo_user: root
  file: path={{ graphistry_install_path }}
        state=directory
        recurse=no
        owner={{ node_user_name }}
        group={{ node_user_group }}
        mode=0775

- name: Set ownership of everything in graphistry app install directory and subdirectories
  file: path={{ graphistry_install_path }}
        state=directory
        recurse=yes
        group={{ node_user_group }}
        mode='g+rw'
  sudo: yes
  sudo_user: root

- name: Create global nodejs directories
  file: path={{ item }}
        state=directory
        owner=root
        group=graphistry-dev
        mode='u=rwx,g=rwxs,o=rx'
  sudo: yes
  with_items: npm_subdirs | difference(["{{ graphistry_install_path }}"])

- name: Set ACL defaults on npm global paths for specific groups
  acl: name={{ item[0] }}
       state=present
       etype=group
       entity={{ item[1].group }}
       permissions={{ item[1].permissions }}
       default=yes
  sudo: yes
  with_nested:
    - npm_subdirs
    - npm_group_permissions

- name: Set ACL defaults on npm global paths for specific groups
  acl: name={{ item[0] }}
       state=present
       etype=group
       entity={{ item[1].group }}
       permissions={{ item[1].permissions }}
       default=yes
  sudo: yes
  with_nested:
    - npm_subdirs
    - npm_group_permissions

- name: Set default user ACLs on global nodejs directory
  acl: name={{ item }}
       state=present
       etype=user
       permissions=rwx
       default=yes
  sudo: yes
  with_items: npm_subdirs

- name: Set default group ACLs on global nodejs directory to allow group access
  acl: name={{ item }}
       state=present
       etype=group
       permissions=rwx
       default=yes
  sudo: yes
  with_items: npm_subdirs

- name: Set default mask ACLs on global nodejs directory
  acl: name={{ item }}
       state=present
       etype=mask
       permissions=rwx
       default=yes
  sudo: yes
  with_items: npm_subdirs

- name: Set mask ACLs on global nodejs directory
  acl: name={{ item }}
       state=present
       etype=mask
       permissions=rwx
       default=no
  sudo: yes
  with_items: npm_subdirs

- name: Find graphistry-dev GID
  group: name=graphistry-dev state=present
  sudo: yes
  sudo_user: root
  register: graphistry_dev_group

- name: Upload npm global config
  template: src=npmrc.j2
            dest={{ npm_global_path }}/etc/npmrc
            owner=root
            group=graphistry-dev
            mode=0644
  sudo: yes

- name: Create directory to hold npm global config shim
  file: path=/usr/etc
        state=directory
        owner=root
        group=root
        mode=0755
  sudo: yes

- name: Symlink default npmrc to our global npmrc
  file: path=/usr/etc/npmrc
        state=link
        src={{ npm_global_path }}/etc/npmrc
  sudo: yes

- name: Disable default nodejs bash config
  file: path=/etc/profile.d/nodejs.sh
        state=absent
  sudo: yes
  sudo_user: root

- name: Configure global Bash profile for npm options
  template: src=Z90-graphistry-nodeglobal.sh.j2
            dest=/etc/profile.d/Z90-graphistry-nodeglobal.sh
            owner=root
            group=root
            mode=0755
  sudo: yes

- name: Install npm v2.12.1
  npm: name=npm
       global=yes
       state=present
       version=2.12.1
  environment: nodecl_env
  sudo: yes

- name: Install node-gyp globally
  npm: name=node-gyp
       global=yes
       state=latest
       executable={{ npm_global_path }}/bin/npm
  environment: nodecl_env
