---
- name: Create npm temp directory
  file: path="{{ npm_temp_path }}"
        state=directory
        recurse=no
        owner={{ node_user_name }}
        group=graphistry-dev
        mode=1777
  sudo: yes
  sudo_user: root

- name: Install Node Source APT repo key
  sudo: yes
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add Node Source APT repo
  sudo: yes
  apt_repository: "repo='deb https://deb.nodesource.com/node {{ ansible_lsb.codename }} main' state=present"
  register: added_node_repo

- name: Add Node Source APT source repo
  sudo: yes
  apt_repository: "repo='deb-src https://deb.nodesource.com/node {{ ansible_lsb.codename }} main' state=present"

- name: Update apt cache
  apt: update_cache=yes
  sudo: yes
  when: added_node_repo.changed

- name: Install Kerberos dev libs (needed for MongoDB node module)
  apt: pkg=libkrb5-dev state=installed update_cache=yes cache_valid_time=600
  sudo: yes
  sudo_user: root

- name: Install Node.js
  apt: name=nodejs state=latest update_cache=yes cache_valid_time=600
  sudo: yes

- { include: clear_caches.yml }

- name: Create graphistry app install directory
  sudo: yes
  sudo_user: root
  file: path={{ graphistry_install_path }}
        state=directory
        recurse=no
        owner={{ node_user_name }}
        group={{ node_user_group }}
        mode=0775

- name: Set ownership of everything in graphistry app install directory and subdirectories
  file: path={{ graphistry_install_path }}
        state=directory
        recurse=yes
        group={{ node_user_group }}
        mode='g+rw'
  sudo: yes
  sudo_user: root

- name: Disable default nodejs bash config
  file: path=/etc/profile.d/nodejs.sh
        state=absent
  sudo: yes
  sudo_user: root

- name: Install npm v2.14.0
  npm: name=npm
       global=yes
       state=present
       version=2.14.0
  environment: nodecl_env
  sudo: yes
