---
- name: "Create default group for user {{ user }}"
  sudo: true
  group: name='{{ user }}'

- name: "Create user '{{ user }}'"
  user: name='{{ user }}'
        groups='{{ group_membership | union([user]) | join(",") }}'
        group='{{ user }}'
        shell=/bin/bash
        append=yes
  sudo: true

- name: "Check if we have a SSH pubkey for {{ user }}"
  local_action:
    module: stat
    path: "{{ playbook_dir }}/roles/users/files/ssh_keys/{{ user }}.pub"
  sudo: no
  register: pubkey_file

- name: "Set {{ user }}'s SSH key"
  authorized_key: user='{{ user }}' key='{{ lookup('file', 'ssh_keys/' +  user + '.pub') }}'
  sudo: true
  sudo_user: "{{ user }}"
  when: pubkey_file.stat.exists

# - name: "Allowing {{ user }} to sudo without entering a password"
#   sudo: true
#   lineinfile: "dest=/etc/sudoers.d/50-graphistry-users
#               line='{{ user }} ALL=(ALL) NOPASSWD:ALL'
#               state=present
#               create=yes
#               owner=root
#               group=root
#               mode=0440
#               validate='visudo -cf %s'"

- { include: configure_user.yml, sudo: yes, sudo_user: "{{ user }}", homedir: "/home/{{ user }}" }