---
- name: Create graphistry-dev group
  group: name=graphistry-dev
  sudo: yes
  sudo_user: root

- name: Configure sudo for graphistry-dev group
  copy: src=40-graphistry-dev.sudoers
        dest=/etc/sudoers.d/40-graphistry-dev
        owner=root
        group=root
        mode=0440
        validate='visudo -cf %s'
  sudo: yes

- name: Set permissions on Graphistry Ansible directory
  file: path="{{ ansible_files }}"
        group=graphistry-dev
        mode="g+rw"
        recurse=yes
  sudo: yes

- name: Create group for users authorized to use the Ansible user's SSH agent auth socket
  group: name=sshauthsock
  sudo: yes
  sudo_user: root

- name: Create ~/.ssh directory
  file: path="~/.ssh"
        state=directory
        mode=0710
  sudo: no

- name: Upload ~/.ssh/rc script, which allows us to use SSH agent forwarding under `sudo`
  template: src=sshrc.j2
            dest="~/.ssh/rc"
            mode=0744
            validate='/bin/sh -n "%s"'
  sudo: no

- name: Create groups
  group: name={{ item }}
  with_items: user_groups
  sudo: yes

- name: Create users
  # The complicated 'groups' filter basically sets users.groups to default_groups if it's undefined;
  # omits the "groups" argument if user.groups is empty/no value; or just uses user.groups.
  user: name='{{ item.username }}'
        groups='{{ item.groups|default(default_groups)|default([], true)|join(",")|default(omit, true) }}'
        shell=/bin/bash
  with_items: users
  sudo: true

- name: Set users' SSH key
  authorized_key: user='{{ item.username }}' key='{{ lookup('file', item.pubkey) }}'
  sudo: true
  sudo_user: "{{ item.username }}"
  when: item.pubkey|default(False)
  with_items: users

- name: Run ~/.ssh/rc (it may not get run after uploading if SSH pipelining is on in Ansible)
  shell: ~/.ssh/rc
  sudo: no

- name: Do extra user tasks for user 'mtorok'
  include: mtorok.yml
  when: '{{ "mtorok" in users|map(attribute="username") }}'
  tags:
    - mtorok
    - users

- name: Kill zombie ssh-agent processes (it's OK if this fails)
  command: killall ssh-agent
  ignore_errors: true
  sudo: yes
  sudo_user: root
