---
- name: Create graphistry-dev group
  group: name=graphistry-dev
  sudo: yes

- name: Configure sudo for graphistry-dev group
  copy: src=40-graphistry-dev.sudoers
        dest=/etc/sudoers.d/40-graphistry-dev
        owner=root
        group=root
        mode=0440
        validate='visudo -cf %s'
  sudo: yes

- name: Set permissions on Graphistry Ansible directory
  file: path="{{ ansible_files }}"
        group=graphistry-dev
        mode="g+rw"
        recurse=yes
  sudo: yes

- { include: create_user.yml, user: www, group_membership: [] }
- { include: create_user.yml, user: leo }
- { include: create_user.yml, user: thibaud }
- { include: create_user.yml, user: quinn }
- { include: create_user.yml, user: paden }
- { include: create_user.yml, user: ubuntu }
- { include: create_user.yml, user: mtorok }
- { include: mtorok.yml, tags: [ 'mtorok' ] }
