---
- name: Ensure central app install path is owned by user 'www'
  sudo: yes
  sudo_user: root
  file: path={{ graphistry_install_path }}
        state=directory
        recurse=no
        owner=www
        group=www
        mode=0775

- name: Ensure everything in install path can be read/written to by group 'www'
  sudo: yes
  sudo_user: root
  file: path={{ graphistry_install_path }}
        state=directory
        recurse=yes
        group=www
        mode='g+rw'

- name: Create log directory for central app
  file: path=/var/log/central-app
        state=directory
        owner=root
        group=www
        mode=0775
  sudo: yes
  sudo_user: root

- name: Create directory for client logs
  file: path=/var/log/clients
        state=directory
        owner=root
        group=www
        mode=0775
  sudo: yes
  sudo_user: root

- name: Run central app under Supervisor
  template: src=central.conf.j2
            dest=/etc/supervisor/conf.d/central.conf
            owner=root
            group=graphistry-dev
            mode=0664
  sudo: yes
  sudo_user: root
  notify: Add central to Supervisor

- name: Delete central's old node_modules directory
  file: path={{ graphistry_install_path }}/central/node_modules
        state=absent
  sudo: yes
  sudo_user: root

- name: Clone central repo
  git: repo=git@github.com:graphistry/central.git
       dest={{ graphistry_install_path }}/central
       version="{{ central_module_checkout }}"
       update=yes
       key_file=/home/{{ sudo_user }}/.ssh/deploy_id_rsa
       accept_hostkey=yes
  register: central_updated
  notify: Restart central

- name: Prune unused npm modules from central
  command: npm prune
           chdir="{{ graphistry_install_path }}/central"
  notify: Restart central

- name: Install central module
  npm: path={{ graphistry_install_path }}/central
       state=latest
  environment: cuda_env
  notify: Restart central

- name: Install nginx
  apt: pkg=nginx
       state=latest
       update_cache=yes
       cache_valid_time=600
  sudo: yes
  sudo_user: root
  notify: Restart nginx

- name: Configure nginx (main config file)
  copy: src=nginx.conf
        dest=/etc/nginx/nginx.conf
        owner=root
        group=graphistry-dev
        mode=0664
  sudo: yes
  sudo_user: root
  notify: Restart nginx

- name: Configure nginx (individual config file)
  copy: src={{ item }}
        dest=/etc/nginx/conf.d/{{ item | basename }}
        owner=root
        group=graphistry-dev
        mode=0664
  sudo: yes
  sudo_user: root
  notify: Restart nginx
  with_fileglob:
    - nginx.conf.d/*

- name: Disable nginx default site
  file: path=/etc/nginx/sites-enabled/default
        state=absent
  sudo: yes
  sudo_user: root
  notify: Restart nginx

- name: Configure nginx to proxy to nodejs
  template: src=central.site.j2
            dest=/etc/nginx/sites-enabled/central
            owner=root
            group=www
            mode=0664
  sudo: yes
  sudo_user: root
  notify: Restart nginx