---
# Provisions app servers (that is, the servers running the viz workers and/or cental.)
# This task list contains a few basic tasks common to app servers, but most of the work is done via
# dependencies of this task.

- { include: tmp_mount.yml, tags: [ 'tmp_mount' ] }

- name: Create temp folder for Graphistry data
  file: path="{{ graphistry_temp_path }}"
        state=directory
        recurse=yes
        owner=www
        group=graphistry-dev
        mode=0770
  sudo: yes

- name: Install Supervisor
  apt: pkg=supervisor
       state=latest
       update_cache=yes
       cache_valid_time=300
  sudo: yes

- name: Start Supervisor
  service: name=supervisor
           state=started
           enabled=yes
  sudo: yes

- name: Configure Supervisor
  copy: src=supervisord.conf
        dest=/etc/supervisor/supervisord.conf
        owner=root
        group=root
        mode=0664
  sudo: yes
  notify: Restart Supervisor