---
# Provisions app servers (that is, the servers running the viz workers and/or cental.)

- name: Create Graphistry apps json log folder
  file: path=/var/log/graphistry-json
        state=directory
        owner=www
        group=graphistry-dev
        mode=0775
  sudo: yes

- name: Configure logrotate for Graphisty apps json logs
  copy: src=graphistry-json.logrotate.conf
        dest=/etc/logrotate.d/graphistry-json
        owner=root
        group=root
        mode=0644
  sudo: yes

- name: Force logrotate to rotate Graphistry app json logs
  command: logrotate --force /etc/logrotate.d/graphistry-json
  sudo: yes

- name: Create temp folder for Graphistry data
  file: path="{{ graphistry_temp_path }}"
        state=directory
        recurse=no
        owner=www
        group=graphistry-dev
        mode=0770
  sudo: yes

- name: Install Supervisor
  apt: pkg=supervisor
       state=latest
       update_cache=yes
       cache_valid_time=300
  sudo: yes

- name: Start Supervisor
  service: name=supervisor
           state=started
           enabled=yes
  sudo: yes

- name: Configure Supervisor
  copy: src=supervisord.conf
        dest=/etc/supervisor/supervisord.conf
        owner=root
        group=root
        mode=0664
  sudo: yes
  notify: Restart Supervisor
