---
- name: Create ~/.ssh directory
  file: path="{{ ansible_env.HOME }}/.ssh"
        state=directory
        owner="ubuntu"
        group="ubuntu"
        mode=0700
  sudo: no

- name: Upload deploy SSH key
  copy: src=ssh_keys/deploy.pem
        dest="{{ ansible_env.HOME }}/.ssh/deploy_id_rsa"
        owner="ubuntu"
        group="ubuntu"
        mode=0600

- name: Register SSH deploy key
  shell: 'eval "$(ssh-agent -s)" && ssh-add {{ ansible_env.HOME }}/.ssh/deploy_id_rsa'

- name: Set SSH config to use deploy key on GitHub
  copy: src=ssh.config
        dest="{{ ansible_env.HOME }}/.ssh/config"
        owner="ubuntu"
        group="ubuntu"
        mode=0600
        force=no


- name: Remove deploy SSH key from SSH agent
  command: ssh-add -d /home/{{ item.username }}/.ssh/deploy_id_rsa
  sudo: yes
  sudo_user: "{{ item.username }}"
  when: item.username != "mtorok" or item.username != "ubuntu"
  with_items: users
  ignore_errors: true
  tags:
    - secure_ssh

- name: Delete deploy SSH key
  file: path="/home/{{ item.username }}/.ssh/deploy_id_rsa"
        state=absent
  sudo: yes
  sudo_user: "{{ item.username }}"
  when: item.username != "mtorok" or item.username != "ubuntu"
  with_items: users
  tags:
    - secure_ssh

- name: Delete SSH config
  file: path="/home/{{ item.username }}/.ssh/config"
        state=absent
  sudo: yes
  sudo_user: "{{ item.username }}"
  when: item.username != "mtorok" or item.username != "ubuntu"
  with_items: users
  tags:
    - secure_ssh
