---
- name: Create ~/.ssh directory
  file: path="/home/{{ item }}/.ssh"
        state=directory
        owner="{{ item }}"
        group="{{ item }}"
        mode=0700
  sudo: yes
  sudo_user: "{{ item }}"
  with_items: ssh_configured_users

- name: Upload deploy SSH key
  copy: src=deploy.pem
        dest="/home/{{ item }}/.ssh/deploy_id_rsa"
        owner="{{ item }}"
        group="{{ item }}"
        mode=0600
  sudo: yes
  sudo_user: "{{ item }}"
  with_items: ssh_configured_users_active

- name: Register SSH deploy key
  shell: 'eval "$(ssh-agent -s)" && ssh-add "/home/{{ item }}/.ssh/deploy_id_rsa"'
  sudo: yes
  sudo_user: "{{ item }}"
  with_items: ssh_configured_users_active

- name: Set SSH config to use deploy key on GitHub
  copy: src=ssh.config
        dest="/home/{{ item }}/.ssh/config"
        owner="{{ item }}"
        group="{{ item }}"
        mode=0600
        force=no
  sudo: yes
  sudo_user: "{{ item }}"
  with_items: ssh_configured_users_active
