---
- name: Find deploy keys
  command: find /home -name 'deploy_id_rsa'
  sudo: yes
  register: deploy_keys

- name: Delete deploy keys
  file: path="{{ item }}"
        state=absent
  sudo: yes
  with_items: deploy_keys.stdout_lines

- name: Find SSH configs
  command: find /home -path '*/.ssh/config'
  sudo: yes
  register: ssh_configs

- name: Delete SSH configs
  file: path="{{ item }}"
        state=absent
  sudo: yes
  with_items: ssh_configs.stdout_lines
